### ISSUE TITLE
"Cannot found source code for..." (Cobertura, again)

### ISSUE THREAD

**Issue by medianick** [jenkinsci/code-coverage-api-plugin#105]
This is very similar to #69 (which is now closed), but perhaps even simpler. I have a build job that has been using the `cobertura` plugin like so:

```
cobertura(	                
  coberturaReportFile: '**/cobertura.xml',
  lineCoverageTargets: '60, 0, 0')
```

I just switched to `publishCoverage` in order to try some of its features (such as the `calculateDiffForChangeRequests` settings, which Cobertura lacks), so am using it like this:

```
publishCoverage(
  adapters: [coberturaAdapter('**/cobertura.xml')],
  calculateDiffForChangeRequests: true,
  globalThresholds: [[thresholdTarget: 'Line', unhealthyThreshold: 60.0]],
  sourceFileResolver: sourceFiles('STORE_LAST_BUILD'))
```

However, my build log shows that it was unable to find the source code, e.g.:

```
00:01:03.789  A total of 1 reports were found
00:01:03.792  Source File Navigation is enabled - Current level: STORE_LAST_BUILD
00:01:03.792  8 source files need to be copied
00:01:03.889  Cannot found source file for C:\Jenkins\workspace\Redacted_PR-60\Foo.cs
...
```

In my case, the path it's citing is _exactly_ the same as the location of the file in question on my Jenkins build agent, and matches the `filename` attribute in the Cobertura XML report.

For plugins, I have Cobertura 1.14 and Code Coverage API 1.0.12, both the latest as of today.

Why isn't the plugin finding my source code?

**Comment by Roemer** [comment]
I got the same problem.
When I check in jenkins in the jobs folder, I see that the files were added but their name is wrapped in single quotes ```'```.
See:
```
drwxr-xr-x 3 localadmin localadmin  4096 Aug 27 12:24  archive
-rw-r--r-- 1 localadmin localadmin 25804 Aug 27 12:26  build.xml
-rw-r--r-- 1 localadmin localadmin     0 Aug 27 12:21  changelog4783929012703789261.xml
-rw-r--r-- 1 localadmin localadmin  2760 Aug 27 12:24 'coverage-sources\src\Client\XXX.Presentation\Commands\EmptyDelegateCommand.cs'
-rw-r--r-- 1 localadmin localadmin 14676 Aug 27 12:24 'coverage-sources\src\Client\XXX.Presentation\ViewModels\MainViewModel.cs'
...
```
Might a wrong quoting be the problem somewhere?

**Comment by Roemer** [comment]
Interesting. I had ```.\``` in front of the file paths in the coverage file. after removing them, the files are now in the folder ```coverage-sources``` and can be found correctly.

**Comment by medianick** [comment]
This is still happening with Code Coverage API 1.1.0. The files are still exactly where the log messages say they cannot be found, in the workspace on my agent node (e.g., `C:\Jenkins\workspace\Redacted_PR-60\Foo.cs`), so I don't know what is preventing them from being located. It's not that it's running on an agent vs. the master node, is it? Or some backslash vs. slash normalization issue?

**Comment by medianick** [comment]
I figured it out: I had a `<sources>` value of "." (as a default) in the `cobertura.xml` file that was being passed as input. Once I changed this to the Jenkins workspace (e.g., `C:\Jenkins\workspace\Redacted_PR-60`), the "cannot found" errors went away, and indeed, I now have a "coverage-sources" folder on the master, with the corresponding source code.

I now see a separate issue, which is that the Coverage Report shows this:
```
Source code is unavailable. Some possible reasons are:

* You have specified source file storing level to never save.
* Code Coverage API plugin cannot found source files.
* You do not have sufficient permissions to view this file.
```
I'll close this particular issue assuming that the new issue is different. As I _have_ specified that source code should be saved, and _now_ the Code Coverage API plugin can find my source files, I'm assuming the issue must be permissions of some sort.

**Comment by jojjezlatansson** [comment]
@medianick I have the same problem, did you solve this? I also assume it is something with permissions, but afaik I have configured the permissions correctly between slaves and master, according to [Slave To Master Access Control](https://wiki.jenkins.io/display/JENKINS/Slave+To+Master+Access+Control).
