### ISSUE TITLE
Difference between adapters

### ISSUE THREAD

**Issue by CCFenner** [jenkinsci/code-coverage-api-plugin#106]
What is the difference between the provided and additional plugin adapters? Is there any recommendation which to use?

- `coberturaAdapter`vs. `istanbulCoberturaAdapter`
- `jacoco` vs `jacocoAdapter`

**Comment by cizezsy** [comment]
It depends on which coverage tool you use.

- `cobertura` is the short name of `coberturaAdapter`, you can use it if you are using [Cobertura](https://cobertura.github.io/cobertura/) to generate the report.(`cobertura` has name conflict with cobertura plugin, so you may need to use `coberturaAdapter` first)
- `istanbulCoberturaAdapter ` also has a short name `istanbulCobertura`, you can use it if you are using [Istanbul.js](https://istanbul.js.org/) with its [cobertura reporter](https://istanbul.js.org/docs/advanced/alternative-reporters/#cobertura) to generate coverage report.
- `jacoco` and `jacocoAdapter` should be used if you want to use [JaCoCo](https://www.jacoco.org/jacoco/trunk/doc/) to generate report.
- Also, there is support for [SonarQube Generic coverage](https://github.com/jenkinsci/sonarqube-generic-coverage-plugin), [LLVM-Cov](https://github.com/jenkinsci/llvm-cov-plugin) and [D coverage](https://github.com/jenkinsci/code-coverage-api-plugin/pull/102).

According to your project's language, you need to use different coverage tools. JaCoCo and Cobertura are for Java, Istanbul.js is for JavaScript, SonarQube generic coverage generated by SonarQube, D coverage is for D language, LLVM-Cov is for c and c++(might for more language, but I am not familiar with llvm) :P

If you want to implement other coverage tools, welcome to open a PR to contribute codes.

**Comment by CCFenner** [comment]
Thanks for the clarification. However, is there any difference in the expected format for `coberturaAdapter` and `istanbulCoberturaAdapter`?

We for example use in JS projects the Karma runner with the Karma-Coverage-Plugin which can produce Cobertura reports that in the back again uses Istanbul.

**Comment by cizezsy** [comment]
@CCFenner The expected format is the same, but `istanbulCoberturaAdapter ` has more friendly metrics, like `function` instead of `method` and `directory` instead of `package`.

**Comment by CCFenner** [comment]
Would be nice if this would be determined automatically by the file names from the test report.

![Bildschirmfoto 2019-07-29 um 14 29 58](https://user-images.githubusercontent.com/26137398/62048579-85c35200-b20d-11e9-96e7-4b336d502984.png)

**Comment by cizezsy** [comment]
I think it should be controlled by users, file names are not reliable.

**Comment by cizezsy** [comment]
Feel free to reopen this issue if you have more questions to ask :P

**Comment by reddwarf69** [comment]
Just in case DDG sends another C/C++ developer here:
- Even if you happen to use clang, the llvm-cov plugin seems unmaintained (https://github.com/jenkinsci/llvm-cov-plugin/issues/12)... even if it's not marked for adoption
- There doesn't seem to be any plugin for the gcov JSON format (https://gcc.gnu.org/onlinedocs/gcc/Invoking-Gcov.html)
- So you may be using "gcovr --xml" to generate the information in Cobertura format.

In such a case, coberturaAdapter happens to be unable to find the files in any non-trivial directory structure, while the istanbulCoberturaAdapter works just fine. And FWIW https://plugins.jenkins.io/cobertura/, which doesn't differentiate between "istanbul" and others, can also find the files.
