### ISSUE TITLE
Coverage thresholds getting applied at directory level and build doesn't fail gracefully.

### ISSUE THREAD

**Issue by jpadhye** [jenkinsci/code-coverage-api-plugin#110]
I've specified istanbul coverage targets as follows for one of my modules and marked to fail unhealthhy and unstable builds.
```
      thresholds: [
        [thresholdTarget: 'Conditional', unhealthyThreshold: 85.0, unstableThreshold: 85.0],
        [thresholdTarget: 'Line', unhealthyThreshold: 92.0, unstableThreshold: 92.0],
        [thresholdTarget: 'Function', unhealthyThreshold: 97.0, unstableThreshold: 97.0]
      ]
    ),
...
...
  failNoReports: true,
  failUnhealthy: true,
  failUnstable: true,
```
Snapshot of current module coverage and per directory coverage is attached here.
[Coverage Report screenshot](https://imgur.com/CYk7vhF)

**Expectation**: If the coverage for this module falls below the specified threshold, the build should fail gracefully and the coverage report should be published with message indicating why the build failed. Expectation is similar to current cobertura plugin.

**Observation**: The publisher generates exception for failure encountered at directory level even when module level parameters are met. When a threshold is breached, it generates an exception instead of marking this build as failure and doesn't generate a report for the build.
```
Publishing Coverage report....
A total of 11 reports were found
Source File Navigation is enabled - Current level: STORE_LAST_BUILD
36 source files need to be copied
io.jenkins.plugins.coverage.exception.CoverageException: Publish Coverage Failed (Unhealthy): Conditional coverage in evtOps/elasticsearch is lower than 85.00
	at io.jenkins.plugins.coverage.CoverageProcessor.processThresholds(CoverageProcessor.java:425)
	at io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport(CoverageProcessor.java:107)
	at io.jenkins.plugins.coverage.CoveragePublisher.perform(CoveragePublisher.java:91)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cizezsy** [comment]
@jpadhye If you specify a threshold, it will be applied to all levels. For example, if you specify a `Conditional` threshold, this plugin will check all modules, directories, files...So thresholds getting applied at the directory level is reasonable.

Also, fixed build doesn't fail gracefully in #113 :) thanks a lot~

**Comment by jpadhye** [comment]
@cizezsy  I understand what you are saying and how it is implemented but that's not how the old cobertura plugin worked. Coverage thresholds should be applied at top level. For example: Sometimes there is a constants file which has 2 lines. Only one line gets covered. Overall module coverage might be 90% but that one file has 50%. It doesn't make sense to apply coverage thresholds at that level. Atleast that should be configurable if you don't want that behaviour.

**Comment by jpadhye** [comment]
@cizezsy  Thanks for adding the graceful failure fix.

**Comment by cizezsy** [comment]
@jpadhye Yeah, you are right, will add a config option for it. Thanks!
