### ISSUE TITLE
Question About Cobertura `mergeToOneReport`

### ISSUE THREAD

**Issue by vishalkuo** [jenkinsci/code-coverage-api-plugin#125]
Hi there,

We have a situation where multiple cobertura reports might end up overlapping slightly in the lines they cover. What I want to know is if `mergeToOneReport` only aggregates the coverage hits and produces a holistic view as if we ran tests in serial or if that's not the case. 

Secondly, if I run into a case where I see `WARNING: Unknown parameter(s) found for class type 'hudson.plugins.cobertura.adapter.CoberturaReportAdapter': mergeToOneReport` does that mean my Cobertura plugin is out of date or my code-coverage plugin is out of date?

**Comment by tempora-mutantur** [comment]
Hello @vishalkuo.
The plugin doesn't handle overlapping coverage in reports.
Probably, your Cobertura plugin using some of the newer versions of Code Coverage API and able to process `mergeToOneReport`.

**Comment by uhafner** [comment]
See also #161
