### ISSUE TITLE
REST API endpoints

### ISSUE THREAD

**Issue by PyvesB** [jenkinsci/code-coverage-api-plugin#126]
Hello there!

I'm one of the maintainers of the [Shields project](https://github.com/badges/shields). We provide badges for a wide variety of services and one of our users has requested a new coverage badge based on the Code Coverage API plugin (see https://github.com/badges/shields/issues/3761 and https://github.com/badges/shields/issues/3785). We currently only support Jenkins coverage badges for the Cobertura and JaCoCo plugins through their own specialised APIs.

I'm trying to figure out whether I can easily retrieve the coverage of a job given a Jenkins host and a job name. The Readme indicates the following API endpoint:
`…​/{buildNumber}/coverage/…​/result/api/\{json|xml\}`

What is the second `...` placeholder? I haven't found any documentation about it, and after quite a bit of digging through various GitHub issues, its value seems dependent on the plugin that integrates with the coverage API:
* jacoco__jacoco
* istanbul__coverage_xml
* cobertura_xml
* ...

However, omitting it also seems possible. For instance, the following endpoint just works:
https://jenkins.library.illinois.edu/job/OpenSourceProjects/job/Speedwagon/job/master/1120/coverage/result/api/json?depth=1

Could you please shed some light on these API endpoints?

Thanks in advance!

Pyves

**Comment by cizezsy** [comment]
Hi, sorry for the lack of documentation...

The placeholder here is the path of the element you want to get coverage from. You can just omit it to get the overall coverage. 
```
/coverage/.../result/api/json?depth=1
```
For the `elements` field you can see the coverage of each metric. The `Line` metric and `Report` is the basic metric that all report types have them. Other metrics depend on the coverage adapters you use. Like the `Function` metric is provided by llvm-cov adapter, the `Method` metric is provided by Cobertura and JaCoCO adapters.
```
    "elements" : [
      {
        "denominator" : 5.0,
        "name" : "Report",
        "numerator" : 5.0,
        "ratio" : 100.0
      },
      {
        "denominator" : 26.0,
        "name" : "Group",
        "numerator" : 26.0,
        "ratio" : 100.0
      },
      {
        "denominator" : 122.0,
        "name" : "Package",
        "numerator" : 114.0,
        "ratio" : 93.44262
      },
      {
        "denominator" : 669.0,
        "name" : "File",
        "numerator" : 622.0,
        "ratio" : 92.97459
      },
      {
        "denominator" : 921.0,
        "name" : "Class",
        "numerator" : 850.0,
        "ratio" : 92.290985
      },
      {
        "denominator" : 4929.0,
        "name" : "Method",
        "numerator" : 4360.0,
        "ratio" : 88.45608
      },
      {
        "denominator" : 83791.0,
        "name" : "Instruction",
        "numerator" : 75209.0,
        "ratio" : 89.75785
      },
      {
        "denominator" : 19338.0,
        "name" : "Line",
        "numerator" : 17300.0,
        "ratio" : 89.46117
      },
      {
        "denominator" : 6207.0,
        "name" : "Conditional",
        "numerator" : 5329.0,
        "ratio" : 85.85468
      }
    ],
    "name" : "All reports"
  }
```

You can increase the `depth` to get more details. Like the coverage of the child.

**Comment by PyvesB** [comment]
Thanks for the explanations @cizezsy, this makes much more sense now! I think I'll start with a simple badge: display the overall Line coverage percentage returned by the API. We can easily extend things if users want more customisation possibilities in the future. I'll let you know when our new badges are implemented and live! 😉

**Comment by PyvesB** [comment]
Our new badge based on Code Coverage API is live! For example:
https://img.shields.io/jenkins/coverage/api/https/jenkins.library.illinois.edu/job/OpenSourceProjects/job/Speedwagon/job/master
![](https://img.shields.io/jenkins/coverage/api/https/jenkins.library.illinois.edu/job/OpenSourceProjects/job/Speedwagon/job/master)

**Comment by cizezsy** [comment]
@PyvesB It looks great~ thanks ;)

**Comment by SlamaFR** [comment]
As you can see, this is no longer working and the Multibranch Pipeline seems to be the issue. I tried several API calls but I get a 404 error every time.

Do you know what is going on?
