### ISSUE TITLE
Jacoco Plugin merges coverage from previous jenkins stage 

### ISSUE THREAD

**Issue by kishoretak** [jenkinsci/code-coverage-api-plugin#129]
I'm using Jenkins CI with two-stages- Unit Test and Integration Test.
 stage('Test') {
        mavenBuild([maven_goals: 'clean install javadoc:javadoc'])
      jacoco changeBuildStatus: true, minimumInstructionCoverage: '70'
    }
 stage('IntegrationTest') {
      mavenBuild([maven_goals: "clean -PIntegrationTestOnly  test"])
       jacoco changeBuildStatus: true, minimumInstructionCoverage: '60',inclusionPattern: 
       inclusionPatterns
    }

Even though I'm running clean during Integration Test and as per logs I can see only 1 .exec file (jacoco report-Integrated ) is being processed, the overall coverage data is not correct, these data are same as when I combine .exec result from unit test and integration test.

Is jacoco plugin coverage generated in the second stage is incremental?

Logs -

[JaCoCo plugin] Collecting JaCoCo coverage data...
12:02:23  [JaCoCo plugin] **/**.exec;**/classes;**/src/main/java; locations are configured
12:02:23  [JaCoCo plugin] Number of found exec files for pattern **/**.exec: 4
12:02:23  [JaCoCo plugin] Saving matched execfiles:  /home/jenkins/workspace/-test-client-build_qualitygating/testclient-common/target/jacoco.exec /home/jenkins/workspace/-test-client-build_qualitygating/testclient-libs/target/jacoco.exec /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium/target/jacoco.exec /home/jenkins/workspace/-test-client-build_qualitygating/testclient-utils/target/jacoco.exec
12:02:23  [JaCoCo plugin] Saving matched class directories for class-pattern: **/classes: 
12:02:23  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-common/target/classes 60 files
12:02:24  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-integrationtest/target/classes 7 files
12:02:24  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-libs/target/classes 118 files
12:02:24  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium-utils/target/classes 49 files
12:02:24  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium/target/classes 21 files
12:02:24  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-utils/target/classes 7 files
12:02:24  [JaCoCo plugin] Saving matched source directories for source-pattern: **/src/main/java: 
12:02:24  [JaCoCo plugin] Source Inclusions: **/*.java
12:02:24  [JaCoCo plugin] Source Exclusions: 
12:02:24  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-common/src/main/java 39 files
12:02:24  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-integrationtest/src/main/java 4 files
12:02:24  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-libs/src/main/java 97 files
12:02:24  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium-utils/src/main/java 16 files
12:02:24  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium/src/main/java 15 files
12:02:24  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-utils/src/main/java 6 files
12:02:24  [JaCoCo plugin] Loading inclusions files..
12:02:24  [JaCoCo plugin] inclusions: []
12:02:24  [JaCoCo plugin] exclusions: []
12:02:24  [JaCoCo plugin] Thresholds: JacocoHealthReportThresholds [minClass=0, maxClass=0, minMethod=0, maxMethod=0, minLine=0, maxLine=0, minBranch=0, maxBranch=0, minInstruction=0, maxInstruction=0, minComplexity=0, maxComplexity=0]
12:02:24  [JaCoCo plugin] Publishing the results..
12:02:24  [JaCoCo plugin] Loading packages..
12:02:24  [JaCoCo plugin] Done.
12:02:24  [JaCoCo plugin] Overall coverage: class: 66, method: 49, line: 46, branch: 29, instruction: 44
12:02:24  [JaCoCo plugin] Health thresholds: JacocoHealthReportThresholds [minClass=0, maxClass=0, minMethod=0, maxMethod=0, minLine=0, maxLine=0, minBranch=0, maxBranch=0, minInstruction=0, maxInstruction=0, minComplexity=0, maxComplexity=0]
12:02:24  [JaCoCo plugin] Apply Min/Max thresholds result: SUCCESS

[JaCoCo plugin] Collecting JaCoCo coverage data...
18:19:11  [JaCoCo plugin] **/**.exec;**/classes;**/src/main/java; locations are configured
18:19:11  [JaCoCo plugin] Number of found exec files for pattern **/**.exec: 1
18:19:11  [JaCoCo plugin] Saving matched execfiles:  /home/jenkins/workspace/-test-client-build_qualitygating/testclient-integrationtest/target/jacoco-it.exec
18:19:11  [JaCoCo plugin] Saving matched class directories for class-pattern: **/classes: 
18:19:11  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-common/target/classes 60 files
18:19:11  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-integrationtest/target/classes 7 files
18:19:11  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-libs/target/classes 118 files
18:19:11  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium-utils/target/classes 49 files
18:19:11  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium/target/classes 21 files
18:19:11  [JaCoCo plugin]  - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-utils/target/classes 7 files
18:19:11  [JaCoCo plugin] Saving matched source directories for source-pattern: **/src/main/java: 
18:19:11  [JaCoCo plugin] Source Inclusions: **/*.java
18:19:12  [JaCoCo plugin] Source Exclusions: 
18:19:12  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-common/src/main/java 39 files
18:19:12  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-integrationtest/src/main/java 4 files
18:19:12  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-libs/src/main/java 97 files
18:19:12  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium-utils/src/main/java 16 files
18:19:12  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-selenium/src/main/java 15 files
18:19:12  [JaCoCo plugin] - /home/jenkins/workspace/-test-client-build_qualitygating/testclient-utils/src/main/java 6 files
18:19:12  [JaCoCo plugin] Loading inclusions files..
18:19:12  [JaCoCo plugin] inclusions: [com/salesforce/atf/testclient/extensions/org/license/OrgLicenseUtil.class, com/salesforce/atf/testclient/extensions/org/license/OrgLicenseHelper.class]
18:19:12  [JaCoCo plugin] exclusions: []
18:19:12  [JaCoCo plugin] Thresholds: JacocoHealthReportThresholds [minClass=0, maxClass=0, minMethod=0, maxMethod=0, minLine=0, maxLine=0, minBranch=0, maxBranch=0, minInstruction=0, maxInstruction=0, minComplexity=0, maxComplexity=0]
18:19:12  [JaCoCo plugin] Publishing the results..
18:19:12  [JaCoCo plugin] Loading packages..
18:19:12  [JaCoCo plugin] Done.
18:19:12  [JaCoCo plugin] Overall coverage: class: 100, method: 85, line: 87, branch: 100, instruction: 86
18:19:12  [JaCoCo plugin] Health thresholds: JacocoHealthReportThresholds [minClass=0, maxClass=0, minMethod=0, maxMethod=0, minLine=0, maxLine=0, minBranch=0, maxBranch=0, minInstruction=0, maxInstruction=0, minComplexity=0, maxComplexity=0]
18:19:12  [JaCoCo plugin] Apply Min/Max thresholds result: SUCCESS

**Comment by tempora-mutantur** [comment]
@kishoretak 
Hello.
It looks like you're using different plugin - https://github.com/jenkinsci/jacoco-plugin
You can address your issue there.
Thank you.

**Comment by thatsIch** [comment]
This is indeed the behavior of the jacoco plugin and there is currently no way to overwrite it. I vote to close this issue.
