### ISSUE TITLE
after jenkins's build was aborted,  plugin still copy source files.

### ISSUE THREAD

**Issue by TinyZzh** [jenkinsci/code-coverage-api-plugin#134]
![image](https://user-images.githubusercontent.com/5763397/69698155-84545880-111f-11ea-8272-b710aeefd188.png)

The jenkins's job Build was aborted. but plugin still running and if "Source File Navigation" is enabled the plugin copy source file

**Comment by cizezsy** [comment]
This bug is fixed in https://github.com/jenkinsci/code-coverage-api-plugin/pull/130. I will release a new version once the current open pull requests get merged.

**Comment by cizezsy** [comment]
Fixed in version 1.1.2
