### ISSUE TITLE
[Question] Access merged report within job execution

### ISSUE THREAD

**Issue by wm-khurrum-mujeeb** [jenkinsci/code-coverage-api-plugin#135]
Hello folks,

Does the merged report using `publishCoverage adapters: [jacocoAdapter(mergeToOneReport: true, path: '**/*.xml')]` get stored somewhere where it can be accessed within the execution of the job? If so, what is the default location? In addition, is the file stored as an XML or some other type?

**Comment by tempora-mutantur** [comment]
@wm-khurrum-mujeeb 
Hello.
The report is stored on your Jenkins master, in your build folder, like *var/jenkins_home/jobs/jobname/builds/17* . It's a binary file which contains the plugin's internal representation of the xml reports that you pass.
There are no easy ways to access it from pipelines, for now, you can try this:
1. Use [REST API](https://github.com/jenkinsci/code-coverage-api-plugin/issues/126)
2. Use [Jenkins classes](https://github.com/jenkinsci/code-coverage-api-plugin/blob/dev/src/test/java/io/jenkins/plugins/coverage/CoveragePublisherPipelineTest.java#L131) to access the report

There is an issue about creating a way to do this:
https://github.com/jenkinsci/code-coverage-api-plugin/issues/124

Thank you
