### ISSUE TITLE
Interactive drill-downs not displaying when clicking on summary bar chart

### ISSUE THREAD

**Issue by paragchandra** [jenkinsci/code-coverage-api-plugin#143]
Hi,

I'm trying to use this plugin to display the sort of rich, interactive code coverage results depicted on the project page (https://jenkins.io/blog/2018/08/17/code-coverage-api-plugin-1/). According to that site, it seems like it should be possible to view the details of individual files/packages/etc., down to the color-coded source code. However, I have not been able to get this working - the only thing I can see is the summary bar chart depicted in the screenshot below:

![image](https://user-images.githubusercontent.com/8833632/75065431-ddc9ea80-54b6-11ea-9dde-3b123942ec23.png)

I have created a simple Gradle-based project to reproduce the issue: https://github.com/paragchandra/android-jacoco-sample/tree/PlainJacoco. There is a Freestyle config.xml in that branch that you should be able to import into your own Jenkins instance. This job just clones the repo, executes `./gradlew clean jacocoDebugTestReport`, and then publishes coverage via this plugin. It also uses the HtmlPublisher plugin to archive the HTML report that is produced, so you can verify that Jacoco/Gradle are indeed producing a detailed coverage report.

I'm using v1.1.0 of the code-coverage-api plugin, alongside v3.0.5 of the Jacoco plugin. I was previously using v1.1.3 of code-coverage-api, but I ran headfirst into the "Source file copying fails..." issue described here: https://github.com/jenkinsci/code-coverage-api-plugin/issues/140. Note that after downgrading to v1.1.0 I don't get any errors about not finding required source files,.

**Comment by tempora-mutantur** [comment]
@paragchandra 
Hi.
I tried to reproduce your case - got the following error - Task 'jacocoDebugTestReport' not found in root project 'My Application'.

Also, are you sure that you can't click on the "project" word?

![coverage](https://user-images.githubusercontent.com/19176095/75388107-774d2e00-58f5-11ea-8b9e-b984a8f3c9cd.png)

Thank you

**Comment by paragchandra** [comment]
Ah, I forgot to mention that you need to checkout the `PlainJacoco` branch. But you can disregard this issue completely, because I previously tried clicking everywhere _except_ the project link. Sorry about that! Things are working as expected now.

**Comment by tempora-mutantur** [comment]
@paragchandra 
it is an occasion to make it more obvious to click on

thank you
