### ISSUE TITLE
Exclude source files from copy

### ISSUE THREAD

**Issue by mrozanc** [jenkinsci/code-coverage-api-plugin#148]
Hello,
I found out when the source files are copied in the report they are not the one we expect.
My case is I use lombok and the javadoc is created from a delomboked version of the sources files.
The report shows these files which do not have the same line numbers at all, so everything is highlighted wrong.

As a workaround I perform a cleanDelombok before the publishCoverage part, but it would be nice to have the ability somehow to include or exclude the source files with something like an Ant pattern.

**Comment by tempora-mutantur** [comment]
@mrozanc 
Hello. Source files that the plugin uses are actually those that are specified in your coverage report (Jacoco, Cobertura, etc.). Could you, please, give some more details of how you see this because It's not clear for me how we would specify which files to use as a source from the plugin side.

**Comment by mrozanc** [comment]
Tell me if I'm wrong, but I think the jacoco report does not contains the
path to the directory containing the sources, it contains only the file
paths relatively to the source dirs.

In my case, I use a merged xml report built by using the jacoco merge task.
This report contains the coverage data of all submodules of my project,
allowing to take into account coverage from integration tests.
In the end my source files are located in a submodule while my report is at
the root project level anyway.

Concerning lombok, a delombok task creates sources corresponding to my
original source files for javadoc generation purposes. Unlike usual
generated sources they are never compiled. The class files contains the
line informations from the original source files and that's what jacoco
uses.

The files I see in the Jenkins report are not my files but the ones
delombok produces, but the hilighted lines in those files are the line
numbers from my original files, so everything is highlighted right but on
the wrong file (non instruction lines, empty lines can be highlighted
because in the original file it matches an actual instruction).

I suppose that's because the copy action of the plugin did find the
delombok sources first in my build/ dirs. I didn't dig into the plugin
sources to check how it selects the source files.

**Comment by tempora-mutantur** [comment]
Hi.
Sorry for late response.
You are right, as I understand.
There is code that works for Jacoco and finds the first file that matches and it's probably your delombok sources.
So, your proposal is valid. 
Or, some other elegant way needs to be implemented to resolve Jacoco source files

**Comment by uhafner** [comment]
This should be possible with #265.
