### ISSUE TITLE
publish trend in stage view

### ISSUE THREAD

**Issue by shintasmith** [jenkinsci/code-coverage-api-plugin#149]
I love the new and modern look of the code coverage metrics from this plugin. 

Having to show the code coverage metrics for one build is useful. But seeing trends is what I find _most_ valuable. Did my new code bring down coverage? Did it increase coverage?

Can we show the Trend graph in the stage view of the branch build? I apologized if this is somehow already implemented, but I could not get it to show up in stage view.

![Screen Shot 2020-03-30 at 9 38 58 AM](https://user-images.githubusercontent.com/3640870/77926034-3be2ae00-726b-11ea-80ac-4385f3d159c6.png)

I'd like it to be like the `jacoco` plugin showing Trend here:
![Screen Shot 2020-03-30 at 9 43 46 AM](https://user-images.githubusercontent.com/3640870/77926350-a4ca2600-726b-11ea-85c4-33b79ee2cdf7.png)

**Comment by msallin** [comment]
Exactly what I'm looking for. Would be great to get this feature.

**Comment by uhafner** [comment]
This cannot be done in this plugin, the obsolete stage view needs to be adapted or removed.
