### ISSUE TITLE
fail build when coverage drops

### ISSUE THREAD

**Issue by y0y0z** [jenkinsci/code-coverage-api-plugin#151]
using declerative pipeline syntax in a [`Jenkinsfile`](https://jenkins.io/doc/book/pipeline/jenkinsfile/) and publishing coverage report using [cobertura](https://plugins.jenkins.io/cobertura/) as follows

```groovy
cobertura(
  coberturaReportFile: 'coverage/cobertura-coverage.xml', 
  enableNewApi: true,
  autoUpdateHealth: true,
  autoUpdateStability: true,
  failUnstable: true,
  failUnhealthy: true,
  failNoReports: true,
  onlyStable: false
)
```

also tried using [code coverage api](https://jenkins.io/doc/pipeline/steps/code-coverage-api/) as follows:

```groovy
publishCoverage(
  failUnhealthy: true, 
  calculateDiffForChangeRequests: true,
  failBuildIfCoverageDecreasedInChangeRequest: true,
  failNoReports: true,
  adapters: [
    coberturaAdapter(path: 'coverage/cobertura-coverage.xml')
  ]
)
```

looking at all the documentation i could find, i wasn't able to figure out [what are the instructions to fail the build if coverage drops](https://stackoverflow.com/a/12472638) without using hard-coded thresholds.

i looked at [Add the ability to fail builds in case if code coverage was decreased in a change request build](https://github.com/jenkinsci/code-coverage-api-plugin/pull/122), but still didn't get much out of it.

would appreciate a reference or a [code snippet](https://github.com/jenkinsci/code-coverage-api-plugin/issues/72#issuecomment-612821448).

**Comment by tempora-mutantur** [comment]
@y0y0z 
Hi.
In cobertura you can set some hardcoded threshold and set the `autoUpdateHealth` flag to autoupdate it.

**Comment by y0y0z** [comment]
@tempora-mutantur: this is exactly what i did (look carefully at my post), but it did not achieve what is desired.

could it be a bug?
is there any log i can check to see that cobertura updates the health?

**Comment by tempora-mutantur** [comment]
@y0y0z 

The `autoUpdateHealth` works only in case some static thresholds are set.
In your post I don't see any thresholds.

**Comment by y0y0z** [comment]
@tempora-mutantur: indeed it worked for me.
is the behaviour is documented anywhere? :)

**Comment by kissgyongyver** [comment]
For me it is just updating the static thresholds, but not failing the built
