### ISSUE TITLE
Show Cyclomatic Complexity

### ISSUE THREAD

**Issue by DJViking** [jenkinsci/code-coverage-api-plugin#154]
The Coverage API does not show the Cyclomatic Complexity from JaCoCo.

The JaCoCo plugin did show this from the coverage report in Jenkins.

> JaCoCo also calculates cyclomatic complexity for each non-abstract method and summarizes complexity for classes, packages and groups. According to its definition by McCabe1996 cyclomatic complexity is the minimum number of paths that can, in (linear) combination, generate all possible paths through a method. Thus the complexity value can serve as an indication for the number of unit test cases to fully cover a certain piece of software. Complexity figures can always be calculated, even in absence of debug information in the class files.

Can we get this shown in Coverage API report in Jenkins?

**Comment by uhafner** [comment]
The new step `recordCoverage` is now in [beta testing](https://github.com/jenkinsci/code-coverage-api-plugin/releases/tag/v4.0.0), can you please check if this release helps to solve this issue? Please note that the syntax of the step is totally new and cannot be combined with existing results.
