### ISSUE TITLE
Builds aborted while copying source files leave locked files on the Jenkins master

### ISSUE THREAD

**Issue by medianick** [jenkinsci/code-coverage-api-plugin#158]
We have a project that uses the `sourceFileResolver: sourceFiles('STORE_LAST_BUILD')` setting when calling `publishCoverage`, resulting in the source files being copied to the Jenkins master. However, we've found that if a build gets aborted (e.g., due to a newer build superseding it, or a timeout in another parallel stage) while this copying is happening, the file being copied remains locked on the Jenkins master. This then causes all subsequent builds of the same PR to fail when running the `publishCoverage` step, as it attempts to delete the previous build's `coverage-sources` directory and cannot do so, which looks like this:

```
[2020-04-27T21:40:43.915Z] Publishing Coverage report....
[2020-04-27T21:40:44.953Z] A total of 1 reports were found
[2020-04-27T21:40:44.999Z] Source File Navigation is enabled - Current level: STORE_LAST_BUILD
Unable to delete directory C:\Jenkins\jobs\Foo\jobs\Bar\branches\PR-3680\builds\7\coverage-sources.
```

Once this happens, the only solution is to restart the Jenkins master service, or use a more targeted tool (like Process Explorer) to locate and close the open handle.

I would ideally want the file handle not to be left open by this situation (so that the older build can be cleaned up), but at the very least it would be good to catch this "Unable to delete directory" error and not have it fail the subsequent builds.

Our Jenkins master is running on Windows Server.

**Comment by uhafner** [comment]
This will be fixed with #265 and https://github.com/jenkinsci/prism-api-plugin/pull/2
