### ISSUE TITLE
Source files copy: Define possible paths from plugin step in addition to from xml report

### ISSUE THREAD

**Issue by thomas-riccardi** [jenkinsci/code-coverage-api-plugin#159]
Scenario:
We generate cobertura xml reports from multiple subdirectories, and sometimes even from directories that don't exist on the host (via containers). 
In all cases the files referred to by the xml reports are available somewhere on the host workspace.

Goal:
Resolve the source files with a mapping: this sourceFileResolver should search for files in possible paths passed as extra parameters in the pipeline definition.

I have found #75 but it seems to require defining the extra possible paths in the xml report itself, which is much more complicated for us than defining them in the `publishCoverage` step.

**Comment by uhafner** [comment]
This will be fixed with #265
