### ISSUE TITLE
Make the bars on the graphs clickable

### ISSUE THREAD

**Issue by bdeeming** [jenkinsci/code-coverage-api-plugin#160]
First off thanks for a great plugin!

The bars on the graphs have hovers, which imply that they are clickable. The title also says 'Click for details'. To a user it seems like the plugin is not working. 

In the case of publishing a coberturaAdaptor report, it is made worse by the fact that the top level is also just called 'project' (which is short), in faint grey text. It seems to be the only way to get to the source code view.

I literally didn't see it after trying multiple builds for over 30mins trying to figure out why the source code files weren't showing up, despite no errors in the log. I only found it when I came across this comment here https://github.com/jenkinsci/code-coverage-api-plugin/issues/69#issuecomment-501584458 (they also didn't see it for some time it seems).

![Divided by Group Name](https://user-images.githubusercontent.com/1191341/81772778-d573cf80-953a-11ea-8c7d-b6477634b8cb.png)

**Comment by brions** [comment]
This is the same behavior for the jacocoAdaptor report.  The graphs are visually excellent but they seem as though they should be clickable when they aren't and the clickable links are extremely counter-intuitive: 'project' next to the row (as pictured above) and the title of the report that says '(Click for more details)' but does not indicate on hover at all that it is, itself, a link.

**Comment by uhafner** [comment]
Fixed by #203 (but not yet released).
