### ISSUE TITLE
Github organization multibranch job trending graph

### ISSUE THREAD

**Issue by ImDevinC** [jenkinsci/code-coverage-api-plugin#164]
We use Github Organization scanning to find our jobs, and these jobs have multibranch pipelines inside of them that run on every PR. This plugin works to show the code coverage on the individual PR and the jobs that run for that PR, but is it possible to view the code coverage report on the root job level? This way we could track code-coverage changes for the entire job, and just inside of a single PR

**Comment by TinyZzh** [comment]
not support yet!

**Comment by uhafner** [comment]
I'm not sure if I understand the requirement. E.g., in https://ci.jenkins.io/job/Plugins/job/analysis-model/job/master/1260/coverage/ we have the results for the job (i.e. master build) and for the PRs. What exactly is missing here?

**Comment by ImDevinC** [comment]
@uhafner I'd like to see the aggregated results here: https://ci.jenkins.io/job/Plugins/job/analysis-model/

**Comment by uhafner** [comment]
I don't think that Jenkins supports views on this page. (Maybe it would be possible to show such information by creating a custom view with the dashboard view plugin).
