### ISSUE TITLE
WARNING: Unknown parameter(s) found for class type 'io.jenkins.plugins.coverage.adapter.JacocoReportAdapter': calculateDiffForChangeRequests,sourceFileResolver

### ISSUE THREAD

**Issue by tkleiber** [jenkinsci/code-coverage-api-plugin#165]
Hi!

When I use follwing step in my declarative pipeline

```
publishCoverage adapters: [jacoco(mergeToOneReport: true, path: '**/jacoco/report.xml', sourceFileResolver: sourceFiles('STORE_LAST_BUILD'), calculateDiffForChangeRequests: true)]

```

I get the mentioned warning:

```
WARNING: Unknown parameter(s) found for class type 'io.jenkins.plugins.coverage.adapter.JacocoReportAdapter': calculateDiffForChangeRequests,sourceFileResolver

```
If I then drill down in my Coverage Reports the I see instead of source code:

```
Source
Source code is unavailable. Some possible reasons are:

You have specified source file storing level to never save.
Code Coverage API plugin cannot found source files.
You do not have sufficient permissions to view this file.
```
Are this parameter really not possible for Jacoco?

Kind regards
Torsten

**Comment by tkleiber** [comment]
Does anybody handle issues here?

**Comment by uhafner** [comment]
You need to place the parameters outside of the `jacoco` symbol, see https://github.com/jenkins-infra/pipeline-library/blob/ae4cf5a0b27657f40bc97e55f8830448ceed6e1a/vars/buildPlugin.groovy#L113 for an example

**Comment by tkleiber** [comment]
Thank you, I'm was completely blind, as I have read the documentation! Now all works fine!
