### ISSUE TITLE
Feature Request: Publish Coverage to GitHub as Checks

### ISSUE THREAD

**Issue by XiongKezhi** [jenkinsci/code-coverage-api-plugin#168]
Hi @cizezsy  @jeffpearce, our GSoC project (GitHub Checks API Plugin, see https://www.jenkins.io/projects/gsoc/2020/project-ideas/github-checks/) is progressing well, we now have implemented [the API plugin](https://github.com/jenkinsci/github-checks-plugin) during the coding phase 1 (see our [blog post](https://www.jenkins.io/blog/2020/07/09/github-checks-api-plugin-coding-phase-1/)), so now I'm planning to consume our plugin here to publish the coverage as GitHub checks. 

After discussing with mentors, we would like to publish the whole project coverage statistics as a start, I'll open a draft PR for that soon, but since we all have no experience on this plugin, is there anything I need to notice before I start?

cc @timja @uhafner

**Comment by uhafner** [comment]
Maybe it is helpful to ask for comments in [Gitter](https://github.com/jenkinsci/code-coverage-api-plugin) as well?

**Comment by jeffpearce** [comment]
Hi @XiongKezhi. Looking forward to your PR! I don't have any general thoughts, but if you run into anything you don't understand, I'll try to help. Please make sure to ping me for any code reviews to make sure I see them right away.

**Comment by uhafner** [comment]
Fixed by #169
