### ISSUE TITLE
agent may not mkdirs

### ISSUE THREAD

**Issue by rompic** [jenkinsci/code-coverage-api-plugin#173]
Hi,
17:54:12  Starting copy source file example.java. 
17:54:13  io.jenkins.plugins.coverage.exception.CoverageException: java.io.IOException: Failed to deserialize response to UserRequest:hudson.FilePath$WritePipe@4a8e9504: java.lang.SecurityException: agent may not mkdirs D:\Jenkins\builds\org\proj\PR-3181\8\coverage-sources
17:54:13  See https://jenkins.io/redirect/security-144 for more details

It works as expected if I deactivate Slave To Master Access Control.
Is this something that could be fixed in the plugin?
If not: which Method do I have to whitelist?

**Comment by uhafner** [comment]
Will be fixed with #265
