### ISSUE TITLE
Make logging less verbose

### ISSUE THREAD

**Issue by carlfischerjba** [jenkinsci/code-coverage-api-plugin#175]
Could the following log statements be disabled by default? Or maybe Jenkins already provides a way to do this? They generate lots of messages is the Jenkins log files and make it harder to spot issues.

https://github.com/jenkinsci/code-coverage-api-plugin/blob/5b729c002dd01e2206c912e19072de4ab88c1ed2/src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java#L88

https://github.com/jenkinsci/code-coverage-api-plugin/blob/5b729c002dd01e2206c912e19072de4ab88c1ed2/src/main/java/io/jenkins/plugins/coverage/source/DefaultSourceFileResolver.java#L103

**Comment by uhafner** [comment]
This will be fixed with #265
