### ISSUE TITLE
Expose coverage metrics as token macro

### ISSUE THREAD

**Issue by savornicesei** [jenkinsci/code-coverage-api-plugin#178]
Hi all,

Along with the test results and [msbuild warnings and open tasks](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#token-macro-support) I want to add to the build summary email the total coverage / branch coverage / line coverage.
Is it possible to expose those details or it's something OpenCover Plugin should do (It's a .NET project)?

Thank you.

**Comment by uhafner** [comment]
This is something that can be added here. Interested in providing such a pull request?
