### ISSUE TITLE
Use echarts-api plugin

### ISSUE THREAD

**Issue by timja** [jenkinsci/code-coverage-api-plugin#182]
Remove our local copy of echarts:

https://github.com/jenkinsci/code-coverage-api-plugin/blob/master/src/main/webapp/scripts/echarts.min.js

and switch to using the [API plugin](https://github.com/jenkinsci/echarts-api-plugin)

That will mean only one copy of echarts per page, and means we don't have to maintain echarts etc

fyi @uhafner

**Comment by uhafner** [comment]
Yes, this is already tracked as https://issues.jenkins.io/browse/JENKINS-62633. 

Two issue trackers are not really useful...

**Comment by timja** [comment]
Only 5 open issues there, and none raised by users, probably should just close them all and maybe delete the component

**Comment by simonsymhoven** [comment]
closes #197.
