### ISSUE TITLE
Diff without requiring changerequest

### ISSUE THREAD

**Issue by Rogue-14** [jenkinsci/code-coverage-api-plugin#190]
Would like to be able to diff coverage without having to do a changerequest. In other words, a way to manually specify all the options like target branch that it's automatically getting from the changerequest to do the diff.

**Comment by uhafner** [comment]
I would recommend that we replace that part of the code with the new [reference build](https://github.com/jenkinsci/git-forensics-plugin#reference-build) of the Git forensics plugin. Then this kind of delta can be used by all consumers.

**Comment by uhafner** [comment]
Fixed with #199 .
