### ISSUE TITLE
failBuildIfCoverageDecreasedInChangeRequest should not fail if no code changed

### ISSUE THREAD

**Issue by fuzzybair** [jenkinsci/code-coverage-api-plugin#191]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.263.1
OS: Linux - 4.15.0-136-generic
---
sonar:2.12
blueocean-core-js:1.24.3
git:4.4.4
cobertura:1.16
[Many others as this is a shared server]
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
OS: Linux - 4.15.0-136-generic
```

### Reproduction steps

We have several items that are not code related in our repository (e.g. documentation, images, etc.). when we have a pull request that is strictly non code the Pull Request can fail. The failure seems to be related to a rounding difference between the stored and calculated values.
Possible solutions:
* Add a level of tolerance to failBuildIfCoverageDecreasedInChangeRequest to account for the rounding.
* Always round down before storing the value
* Use the same precision with stored and calculated.

### Results

Here is our configuration for the code coverage.
```
      publishCoverage adapters: [coberturaAdapter(mergeToOneReport: false, path: 'codeCoverageReports/Cobertura.xml')],
        calculateDiffForChangeRequests: true, failNoReports: true, failUnhealthy: false, failUnstable: true, failBuildIfCoverageDecreasedInChangeRequest: true,
        globalThresholds: [[thresholdTarget: 'Line', unhealthyThreshold: 85.0, unstableThreshold: 80.0]], sourceFileResolver: sourceFiles('STORE_LAST_BUILD') 
```
Expected result:

failBuildIfCoverageDecreasedInChangeRequest should not fail if there are not any associated code changes. 

Actual result:

We have observed values indicated coverage changed on these pull request between -0.004% and +0.004% if the rounding rounds down from the calculated value the request will show an increase in coverage. But if the request follows after a merge that rounded up it will show a decrease in coverage, and therefore fail the check.

**Comment by reshadatavid** [comment]
This is still a problem. Happening because of Floating point rounding error (happens in and other languages frequently).

**Comment by uhafner** [comment]
> This is still a problem. Happening because of Floating point rounding error (happens in and other languages frequently).

I hope this will be fixed when the migration to the new model is fixed, see #512 for details.

**Comment by reshadatavid** [comment]
Also is it possible to get coverage data in groovy. What I want to do is, instead of relying on fail via plugin, I would take up data in groovy and do necessary calculations

**Comment by uhafner** [comment]
Yes, this might be possible. But looks a little bit like the wrong approach.

**Comment by reshadat** [comment]
> approach

True, but right now the build is failing without any changes in coverage, and this seems to be the only way to fix it. Do you have any other suggestions in mind that I can try?

Also can you help me to get the data in groovy?

**Comment by uhafner** [comment]
> > approach
> 
> True, but right now the build is failing without any changes in coverage, and this seems to be the only way to fix it. Do you have any other suggestions in mind that I can try?

Yes, simply try to fix the bug. This should be simpler than rewriting the same code in Groovy. 
Or check out the new source code and experiment with this version if it fixes the problem.

> 
> Also can you help me to get the data in groovy?

**Comment by fuzzybair** [comment]
@reshadat Thanks for taking a look at this. It has been bothering my team for a while, but not being java developers it is a little out of our skill set. Let me know if there is anything I can do to help test the change.

**Comment by reshadat** [comment]
Thanks @fuzzybair . I have raised a PR and added sufficient tests to prove that it works. However, I am not sure of the release cycles and versioning. @uhafner  Please let me know if I need to do anything for releasing this (upgrading version of plugin etc)
