### ISSUE TITLE
Compare coverage with PR target doesn't work properly since integrating with git forensics

### ISSUE THREAD

**Issue by Cetlan** [jenkinsci/code-coverage-api-plugin#211]
I apologize that this won't really fit into the proper bug report format, and I hope I won't offend with this suggestion since I believe there's some maintainer overlap between the plugins, but would it be possible to consider going back to the "old" way of detecting the target branch for PR coverage diffs pre-git-forensics?

I filed a related bug against git-forensics for it taking the wrong reference branch for PRs, but realistically git forensics seems like complete overkill, and possibly the wrong tool. Before the integration of git forensics, the code coverage api found the build for the PR's target branch and compared against that. That seems like all it needs to do for `calculateDiffForChangeRequests`. The more complicated "reference build" check that git forensics does seems entirely unnecessary for this purpose. And needing to add extra steps to a pipeline to trigger reference build detection just to make `calculateDiffForChangeRequests` work when it simply worked out of the box before just seems like clutter (not to mention it makes it hard to add to an existing repository, and could simply fail when dealing with multiple branches since there might not be a reference build detectable by git-forensics depending on the repository history and when git-forensics was added because it relies on tracking the commits in the builds).

I'm currently limited to running coverage api 1.3.2 because anything after that uses git-forensics, which is unfortunate because 1.3.3 might have fixed a bug I filed on the coverage API.

**Comment by uhafner** [comment]
> I filed a related bug against git-forensics for it taking the wrong reference branch for PRs

Yes I have seen that bug report. It seems that the detection does not always work currently. 

> but realistically git forensics seems like complete overkill, and possibly the wrong tool. 

Well, I see it differently: the forensics-api should be the standard tool to detect reference builds. All other plugins should use it rather than implement the same feature again and again in a non-SCM plugin. From an architectural viewpoint it does not make sense that the coverage plugin computes the reference build on its own. So rather than spending time to re-integrate the SCM code into a non-SCM plugin we should spend the time and improve the detection of the forensics-api plugin.

> Before the integration of git forensics, the code coverage api found the build for the PR's target branch and compared against that. 

This was only true for branch source projects. 

> That seems like all it needs to do for calculateDiffForChangeRequests. The more complicated "reference build" check that git forensics does seems entirely unnecessary for this purpose.

See above, not everybody is using branch source projects. But I understand, it now requires an additional step and that adds an additional complexity. But if the reported bugs are fixed, then it should behave as before. Or am I missing something?

**Comment by Cetlan** [comment]
Hey, thanks for the response. If both of the bugs I filed on git-forensics are fixed, then code coverage might work as before. But then what would happen to any code that expects to be able to get information about the previous build from forensics? (because the reference build would no longer be the previous build of course)

It just seemed to me as I was digging through both of these plugins more trying to find a combination that would work for my current setup that forensics and coverage have two very different concepts of a reference build. Coverage's "calculateDiffForChangeRequests" seems concerned with one specific definition (the latest applicable target branch's build), and forensics' definition of "reference" is somewhat flexible, but includes things like "previous build in the job" that have nothing at all to do with PRs.

My concern would be that adding additional logic to the forensics singular reference build to try to account for this conflates these two ideas of a "reference" in a way that may not always be correct, so it seemed simpler to have code coverage do it's previous PR-based check, and let forensics do any and all acrobatics needed to find a more general reference that may not be in any way related to a multibranch PR, rather than mixing the concepts. But if the plan is to expand code coverage to work with branches and PRs that are in freestyle/etc projects that don't support multibranch, then yeah, I can see that not being feasible.

I have a gut feeling that one generic reference build might not be appropriate in all cases, but given that it sounds like future plans for the coverage aren't compatible with the simple check it was doing, I'm happy to close this with the caveat that I'm going to try very very hard once this is working again to find a corner case where you need a separate concept of the reference build (previous build in the PR job vs the PR target's build). ;)
