### ISSUE TITLE
Make colors configurable

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/code-coverage-api-plugin#221]
Currently, all colors are hard-coded. It would be helpful, if those could be changed by the user. The following Colors that should be configurable:
- trend chart line and branch color
- treemap covered vs. missed percentage
- coverage column: coverage percentage

Making the color palette color blind friendly would be helpful as well. Maybe it makes sense to provide a global color scheme that will be used by other plugins as well.

# Trend chart colors

Trend chart color configuration is the easiest of the above color configurations. In order to change the default trend configuration dialog you need to create a new custom dialog that extends the existing dialog. You can follow the same concept as in the [forensics API plugin](https://github.com/jenkinsci/forensics-api-plugin/blob/master/src/main/resources/io/jenkins/plugins/forensics/miner/ForensicsJobAction/floatingBox.jelly) or [warnings plugin](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/charts.jelly).
- create the chart
- create a function that stores the dialog values into a JSON configuration object
- create a function that fills the dialog values from a JSON configuration object

To select the actual color, you can use the default input color selector, see [example in pull-request-monitoring plugin](https://github.com/jenkinsci/pull-request-monitoring-plugin/blob/master/src/main/resources/modals/add-portlet.jelly#L127).

**Comment by Mr-DG-Wick** [comment]
I'd like to work on this. Can you assign this to me and guide me on how to go about this?

**Comment by uhafner** [comment]
The first thing we need is to prepare your development environment. How familiar are you with Jenkins and plugin development? Do you already have a Jenkins instance with this plugin? 

If not then I would recommend, that you install my [development envirnment](https://github.com/uhafner/warnings-ng-plugin-devenv). This helps to set up coding and deploying to a real Jenkins instance. If that works, we can start talking about the requirements, if that is ok for you.

**Comment by Mr-DG-Wick** [comment]
> How familiar are you with Jenkins and plugin development? Do you already have a Jenkins instance with this plugin?

I am a complete newbie into Jenkins and plugin development. But I am willing to learn and want to contribute to it in the long run. 
I am not that focussed on the hacktoberfest label, I will contribute anyways. Will my being a newbie be a problem?

**Comment by uhafner** [comment]
No, that is fine! Everybody started as a newbie. Most issues that I filed are especially a good starting point for beginners.

**Comment by uhafner** [comment]
All colors are now based on the Jenkins theme, so changing the colors does not make sense here, this should be a global option.
