### ISSUE TITLE
Source code not visible with dark theme

### ISSUE THREAD

**Issue by shaneray** [jenkinsci/code-coverage-api-plugin#228]
Coverage plugin should use a theme-aware rendering of all UI elements. I.e., it should work well with light *and* dark theme.

Tasks:

- [x] Text striped rows in coverage details are so dark impossible to read on the dark theme background.
- [x] When hovering over a line the text goes black or so dark its impossible to read on the dark theme background.
- [x] Pagination buttons and coverage detail tabs do not match the rest of the UI
- [x] Source code view should be theme-aware

**Comment by stefan6419846** [comment]
Has there been any progress on this? I am still facing issues with the default setup, thus I patch the offending sections through Tampermonkey (lines of interest from a bigger script):

```javascript
    // FIX: Colors for dark mode of coverage pages.
    if (location.pathname.match('/coverage/')) {
        // FIX: Display file coverage data with correct colors.
        const source_table = document.getElementsByClassName('source')[0];
        if (source_table.nodeName != 'TABLE') {
            console.warn(source_table);
        } else {
            source_table.setAttribute('style', 'color: black;');
        }

        // FIX: File coverage and indirect file coverage table display for odd rows.
        ['absolute-coverage-table', 'indirect-coverage-table'].forEach(element_id => {
            const source_table = document.getElementById(element_id);
            if (!source_table) {
                return;
            }
            const style = source_table.getAttribute('style');
            source_table.setAttribute('style', style + '; --bs-body-color: var(--bs-gray-600);');
        });

        // FIX: Labels in the configuration modal.
        const configuration_div = document.getElementById('chart-configuration-coverage-history');
        console.log(configuration_div);
        const head = document.getElementsByTagName('head')[0];
        head.innerHTML += `
        <style type="text/css">
            #chart-configuration-label-coverage-history, label[for="build-domain-coverage-history"], label[for="date-domain-coverage-history"], label[for="builds"], label[for="days"]  {
                color: #6c757d !important;
            }
        </style>
        `
    }
```

**Comment by uhafner** [comment]
> Has there been any progress on this? I am still facing issues with the default setup, thus I patch the offending sections through Tampermonkey (lines of interest from a bigger script):
> 
> ```js
>     // FIX: Colors for dark mode of coverage pages.
>     if (location.pathname.match('/coverage/')) {
>         // FIX: Display file coverage data with correct colors.
>         const source_table = document.getElementsByClassName('source')[0];
>         if (source_table.nodeName != 'TABLE') {
>             console.warn(source_table);
>         } else {
>             source_table.setAttribute('style', 'color: black;');
>         }
> 
>         // FIX: File coverage and indirect file coverage table display for odd rows.
>         ['absolute-coverage-table', 'indirect-coverage-table'].forEach(element_id => {
>             const source_table = document.getElementById(element_id);
>             if (!source_table) {
>                 return;
>             }
>             const style = source_table.getAttribute('style');
>             source_table.setAttribute('style', style + '; --bs-body-color: var(--bs-gray-600);');
>         });
> 
>         // FIX: Labels in the configuration modal.
>         const configuration_div = document.getElementById('chart-configuration-coverage-history');
>         console.log(configuration_div);
>         const head = document.getElementsByTagName('head')[0];
>         head.innerHTML += `
>         <style type="text/css">
>             #chart-configuration-label-coverage-history, label[for="build-domain-coverage-history"], label[for="date-domain-coverage-history"], label[for="builds"], label[for="days"]  {
>                 color: #6c757d !important;
>             }
>         </style>
>         `
>     }
> ```

There is nothing to be done in the coverage plugin. The only missing part is the global styling in the https://github.com/jenkinsci/data-tables-api-plugin.  

Before spending more time in hacking the existing CSS values using Tampermonkey I would rather recommend to invest some more time to create a simpler PR for the plugin that will fix the problems for all users 😄

**Comment by stefan6419846** [comment]
> Before spending more time in hacking the existing CSS values using Tampermonkey I would rather recommend to invest some more time to create a simpler PR for the plugin that will fix the problems for all users

While this would indeed be the cleaner solution, hacking together this script has been much easier for me than deep-diving into the Jenkins code (which I am absolutely not familiar with). Additionally, the fixes do not respect the dark-mode setting at all, and colors/styles are clearly debatable.

> There is nothing to be done in the coverage plugin. The only missing part is the global styling in the https://github.com/jenkinsci/data-tables-api-plugin.

I am not completely sure about this, as I discovered at least three independent issues related to the dark theme:

1. The line-based coverage detail pages uses white text on white or light background. My above code sets the text color to black here.
2. The table display is wrong for odd rows by default and when hovering even rows. My above code basically disables highlighting for odd rows, while fixing the default display.
3. The configuration modal for the history chart is barely readable. **This appears to have been fixed since I last checked it, as it now looks correct with without the fix as well.**

**Comment by Pesa** [comment]
> There is nothing to be done in the coverage plugin. The only missing part is the global styling in the https://github.com/jenkinsci/data-tables-api-plugin.

What about the source file view? Is that handled by the data-tables plugin as well?

This is how it currently looks like for me:
<img width="980" alt="Screenshot 2023-03-15 at 2 47 02 PM" src="https://user-images.githubusercontent.com/83452/225412746-e0948b17-1fe7-470b-b39d-a0feaf4fcf09.png">

The warnings-ng plugin is able to display and highlight source code views just fine (well... it isn't perfect either, but at least it's readable).

**Comment by Pesa** [comment]
Looks like warnings-ng is using https://github.com/jenkinsci/prism-api-plugin for source code rendering. Can this plugin do the same?

**Comment by uhafner** [comment]
Yes, that is the idea at some point. I did not find a way yet to handle the line annotations (coverage) in prism. Interested in trying to add support for prism here?

**Comment by asteele0** [comment]
I'm having the same issue as @Pesa, the source code view is impossible to read with dark mode enabled.

**Comment by uhafner** [comment]
Well, I don't use the dark theme so switching to prism is not on my priory list. 

Since this is a community project that evolves by volunteers it would make sense that the people who are actively using the dark theme would start a joint effort to get that fixed. Simply changing the text colors to use the active Jenkins color would be a first step that can even be contributed by total newbies.

**Comment by uhafner** [comment]
Fixed in https://github.com/jenkinsci/code-coverage-api-plugin/releases/tag/v4.6.0
