### ISSUE TITLE
Code Coverage Report is overwritten when calling publishCoverage twice

### ISSUE THREAD

**Issue by rompic** [jenkinsci/code-coverage-api-plugin#236]
### Version report

Jenkins and plugins versions report:
Code Coverage api plugin 2.0.2
Jenkins 2.303.2

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Windows 10
```

### Reproduction steps
- Call publishCoverage twice in a pipeline (with or without tag) using two different adapters (e.g. jacocoAdapter, coberturaAdapter)
- Only the latest report is available via the "Coverage Report" menu item
-  With earlier version of the plugin both reports were published
![image](https://user-images.githubusercontent.com/6322123/137753951-736153ac-339a-48dd-b6de-865f8cd816f6.png)

### Results

Expected result:
Either two different toplevel links are created or both reports are shown via the same link

Actual result:
Only the latest report is available

**Comment by forrestxm** [comment]
This is a serious bug impacting our consumption of 2.0.2, we have to rollback to 1.1.6 to see all the reports. When can we have a fix?

**Comment by gokhanoner** [comment]
@uhafner +1 for different URLs. Having 2 different results in the left side menu, possible using tag or any other param to modify it, will make it much more clear. Is there a plan for this? If not, I can contribute, since we're also using this plugin heavily & I don't like the idea of downgrading the plugin.

**Comment by chickenkiller** [comment]
+1 for different URLs as well!

**Comment by uhafner** [comment]
The new step `recordCoverage` is now in [beta testing](https://github.com/jenkinsci/code-coverage-api-plugin/releases/tag/v4.0.0), can you please check if this release helps to solve this issue? Please note that the syntax of the step is totally new and cannot be combined with existing results.

**Comment by mheinzerling** [comment]
Finally found some time to test the update. With two pipeline branches and the following segments, I got the expected two reports and could remove my stash-and-postprocessing hack. Thanks.

```
recordCoverage (
	id: 'coverage-java',
	name: 'Coverage Java',
	tools: [[pattern: 'build/report.xml']],
	....
)
```

```
recordCoverage(
	id: 'coverage-vue',
	name: 'Coverage Vue',
	tools: [[parser: 'COBERTURA', pattern: 'build/jestcoverage/cobertura-coverage.xml']],
	...
)
```
