### ISSUE TITLE
Publish failed check for coverage drop

### ISSUE THREAD

**Issue by Cetlan** [jenkinsci/code-coverage-api-plugin#256]
### Feature Request

There doesn't seem to be any way to configure coverage to publish a failed check if coverage drops vs the reference build.. The entire build can be failed, but if the only reason for that failure is a drop in coverage, the check won't reflect that - it will show as a success because there's no code path that sets a failure message if the coverage diff is negative.

It would be good if the published check would reflect a failure in the check if the build is failed because of it.
It would be _great_ if it could report the drop in the check (or be configured to report it) even if failBuildIfCoverageDecreasedInChangeRequest is set false - that way the check could still be used as a warning flag without necessarily failing a build.

**Comment by uhafner** [comment]
We are currently refactoring the quality gates anyway (see PRs for [JENKINS-6694](https://issues.jenkins.io/browse/JENKINS-66994). The idea is to extend that in the following way so we have quality gates for:
- coverage result of the current build (absolute value) - this is the current state
- coverage result of the current patch (code in the pull request) - this requires knowledge of the changes in the pull request 
- coverage result of the delta current build minus reference build (relative value) - this is your suggestion
