### ISSUE TITLE
Add parser for altcover

### ISSUE THREAD

**Issue by TinyZzh** [jenkinsci/code-coverage-api-plugin#275]
### Dependencies

the [opencover](https://github.com/OpenCover/opencover) has been archived. 
the author suggest the altcover exension.

altcover
1. Cross-platform .  support windows os and linux
2. support .net 2.x above, .net core and mono.

### Feature Request

support [altcover extension](https://github.com/SteveGilham/altcover).

**Comment by uhafner** [comment]
Typically parsers for other formats are provided by volunteers.

**Comment by uhafner** [comment]
If someone wants to volunteer I can offer some help. There is no issue required to add new parsers.
