### ISSUE TITLE
Save source file failed

### ISSUE THREAD

**Issue by TinyZzh** [jenkinsci/code-coverage-api-plugin#281]
### Version report
2.0.4

Jenkins and plugins versions report:

- What Operating System are you using (both controller, and any agents involved in the problem)?

![image](https://user-images.githubusercontent.com/5763397/147333105-cb99b158-f576-4e3f-beb6-70483f239726.png)
![image](https://user-images.githubusercontent.com/5763397/147333405-82b56518-6a94-4982-8d3a-cc9958d7e225.png)

### Reproduction steps

- Build any java project with jacoco plugin

### Results

Expected result:

source file saved

Actual result:

unable to find source file

**Comment by uhafner** [comment]
See #265

**Comment by TinyZzh** [comment]
thx. i will close it!
