### ISSUE TITLE
build coverage report delta is off by factor of 100

### ISSUE THREAD

**Issue by bitrunner** [jenkinsci/code-coverage-api-plugin#360]
### Jenkins and plugins versions report

Jenkins 2.332.1
Code Coverage API 2.0.4

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. do a build
2. do another build with different coverage numbers
3. look at the delta

### Expected Results

Build 189:
![image](https://user-images.githubusercontent.com/19257789/162259562-f81c3ae1-5264-4422-8bd4-94fb0d5493c2.png)

Build 190:
![image](https://user-images.githubusercontent.com/19257789/162260003-2ff379c1-2c15-4283-8fc7-6f1b8603f7a6.png)

One would expect build 190's line delta to be +2.35% and the branch delta to be +1.84% in this circumstance.

### Actual Results

See above.

**Comment by uhafner** [comment]
I think we fixed that in #324. But let's see if that PR Is ready to be merged...
