### ISSUE TITLE
CoveragePercentage vs. Coverage

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/code-coverage-api-plugin#424]
We should create a consistent API for coverages and coverage percentages. See https://github.com/jenkinsci/code-coverage-api-plugin/pull/423

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/180923313-7258cbbd-5cbb-4f8a-8737-6184d037eee4.png)
The coverage trend should also show two decimal points

**Comment by uhafner** [comment]
The new step `recordCoverage` is now in [beta testing](https://github.com/jenkinsci/code-coverage-api-plugin/releases/tag/v4.0.0), can you please check if this release helps to solve this issue? Please note that the syntax of the step is totally new and cannot be combined with existing results.
