### ISSUE TITLE
Check status is not published on PR

### ISSUE THREAD

**Issue by Choi-Sung-Hoon** [jenkinsci/code-coverage-api-plugin#434]
### What feature do you want to see added?

Hi, I'm requesting the feature which publishes check status because it's not reporting the status properly as expected.

I'd like to publish a check status like Github Pull Request Builder (GPRB).

I configured for [Github Checks Plugin](https://plugins.jenkins.io/github-checks/) according to [this document](https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc) and I'm using the plugin in **Github Enterprise** environment.

When I add `Publish Coverage Report` action like below, it runs checks well but it doesn't publish the result to Github, which means it doesn't call Github API to set the check status.

![image](https://user-images.githubusercontent.com/33472400/180872181-df7b0045-3048-4ee4-9edc-50ba230905b6.png)

If I set the `Code Coverage` check to be displayed forcefully, it always remains `Expected` like below.

![image](https://user-images.githubusercontent.com/33472400/180872408-adfbb81e-d1d2-4d77-baa9-262435a5778e.png)

Jenkins Console Output:
![image](https://user-images.githubusercontent.com/33472400/180872604-c47f0160-38f4-471a-864f-211d0ed1162f.png)

As you can see the log, [Github Checks Plugin](https://plugins.jenkins.io/github-checks/) and [Code Coverage API Plugin](https://plugins.jenkins.io/code-coverage-api/) works well.

I found out that [POST statuses API](https://docs.github.com/en/enterprise-server@3.2/rest/commits#create-a-commit-status) is not called after [check_suite APIs](https://docs.github.com/en/enterprise-server@3.2/rest/checks/suites) by checking `Recent Deliveries` in `Github App Settings` > `Advanced` , where I can see what events are delievered:
![image](https://user-images.githubusercontent.com/33472400/180874218-b1ba23f6-7ba4-4fd0-a12c-376c4dbcc108.png)

Could you review this feature request for better result UI?

Thank you.

**Comment by uhafner** [comment]
This seems to be a problem not related to the plugin. Maybe an authentication or network problem? Do other Jenkins checks work? We use those checks in all of our plugin builds: https://github.com/jenkinsci/code-coverage-api-plugin/pull/429

**Comment by Choi-Sung-Hoon** [comment]
> Do other Jenkins checks work?

No, all other Jenkins checks remains `Expected` on PR.

I think it shouldn't receive events in `Recent Deliveries` if the authentication was a problem.

It's weird that only POST statuses API is not callled except for all other APIs such as `check_run`, `check_suite`.

Do you have any prerequisites list for the plugin?

I would appreciate if you share a standard guide to setup the plugin.

<br>

FYI:

I installed GitHub App in an organization and set permissions & events for the app.

Further I installed the app to a repository and added the app with private key to Jenkins credentials.

I guess it should haven't deliver any event if the authentication or network was the problem.

<br>

Maybe `Checks API` plugin or `GitHub Checks` plugin is a problem?

Do you have any guess?

**Comment by Choi-Sung-Hoon** [comment]
I found out the solution.

If you are using the plugin with `Github Pull Request Builder` plugin, you should use `${ghprbActualCommit}` instead of `${sha1}` in Branch Specifier like below.

![image](https://user-images.githubusercontent.com/33472400/180923318-676dfd63-6bd2-4bd7-8f69-a999d5298070.png)

When the plugin builds the PR, it changes the raw SHA during the build.

In order for the coverage to show on PR, we need to report the initial SHA variable, not the modified one.

After you change the `Branch Specifier`, the check statuses are displayed properly.

![image](https://user-images.githubusercontent.com/33472400/180923716-fbf62632-d313-4697-bc27-a8818181213a.png)
