### ISSUE TITLE
Painting does not clean up temporary directories

### ISSUE THREAD

**Issue by stefan6419846** [jenkinsci/code-coverage-api-plugin#441]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.361
  OS: Linux - 5.3.18-150300.59.71-default
  ---
  [...]
  code-coverage-api:3.0.4
  [...]
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

openSUSE Leap 15.3

### Reproduction steps

1. Configure a coverage reporter for the build pipeline (Python using *coverage.py* in this case).
2. Wait for the coverage report to have been generated:

```
[Coverage] Reference build recorder is not configured
[Coverage] -> No reference build defined, falling back to previous build
[Coverage] -> Found no reference result in reference build
[Coverage] Obtaining action of reference build
[Coverage] Reference build recorder is not configured
[Coverage] -> Found no reference result in reference build
[Coverage] Executing source code painting...
[Coverage] Painting 701 source files on agent
[Coverage] Searching for source code files in:
[Coverage] -> /home/jenkins/.some-agent/workspace/system/src
[Coverage] -> /home/jenkins/.some-agent/workspace/system/src/main/java
[Coverage] -> finished painting successfully
[Coverage] -> zipping sources from folder '/home/jenkins/.some-agent/workspace/system/coverage' as '/home/jenkins/.some-agent/workspace/system/coverage-sources.zip'
[Coverage] Copying painted sources from agent to build folder
[Coverage] -> extracting...
[Coverage] -> done
[Coverage] Finished coverage processing - adding the action to the build...
```

3. Have a look at the temporary directory (`/tmp` in my case).

### Expected Results

Temporary data is being cleaned automatically, leaving no `coverage\d+` directories with each directory containing a rendered coverage HTML file behind.

### Actual Results

More than 2000 (randomly named) directories for each run which includes coverage reporting, which do not appear to be used at all. For Jenkins servers with tons of pipelines which are executed at a regular basis, this will quickly fill up the available disk space unnecessarily.

**Comment by stefan6419846** [comment]
After the initial report, I did some research on how the painting actually is implemented and how the directories and files are used. It seems like the current implementation basically does the following for each source file:

* Create a temporary directory with a random name.
* Paint to a file with the transformed source file path inside this random directory.
* Compress the rendered file into a ZIP file with the same name inside the *coverage* sub-directory of the workspace.

Finally, the *coverage* directory of the workspace will be zipped into a *coverage-sources.zip* file.

Given this, the following question arises for me: Why is there no common random temporary directory which will be used for painting all files? From my understanding of the code, this should not have any disadvantages, but would generate about half of the file system objects (id est directories and files). Unexpected clashes of the sanitized filename are not considered for now anyway. With only one common base folder, cleaning up directories in case of some failure should become much easier as well, as otherwise one might end with Bash refusing to run *rm* due to too many parameters.

Apart from this, the real culprit seems to be roughly at the following line, where the painted file is being zipped into the workspace, without actually removing it afterwards: https://github.com/jenkinsci/code-coverage-api-plugin/blob/815f1e780dd33b078cdab19eb71a8b2555dff4f5/plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/code/SourceCodeFacade.java#L454

**Comment by stefan6419846** [comment]
After I finally managed to get the recommended development environment to correctly set up on a spare Ubuntu 22.04 device (the default Maven from the official repositories is too old, which is only detected after some compiling has already taken place; additionally, I got some timeouts when downloading the required packages), I tried to find a suitable solution for this issue.

It seems like the following patch would do the job:

```diff
diff --git a/plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/code/SourceCodeFacade.java b/plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/code/SourceCodeFacade.java
index 9f1036e..7455340 100644
--- a/plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/code/SourceCodeFacade.java
+++ b/plugin/src/main/java/io/jenkins/plugins/coverage/model/visualization/code/SourceCodeFacade.java
@@ -381,14 +381,21 @@ public class SourceCodeFacade {
                 sourceDirectories.forEach(dir -> log.logInfo("-> %s", dir));
             }
             FilePath workspace = new FilePath(workspaceFile);
+            Path temporaryPaintedFilesDirectory = getTemporaryDirectory(log);
+            if (temporaryPaintedFilesDirectory == null) {
+                return log;
+            }
 
             try {
                 FilePath outputFolder = workspace.child(directory);
                 outputFolder.mkdirs();
 
                 Charset charset = getCharset();
+
+                log.logInfo("Using temporary directory %s for painting", temporaryPaintedFilesDirectory);
                 int count = paintedFiles.parallelStream()
-                        .mapToInt(file -> paintSource(file, workspace, sourceDirectories, charset, log))
+                        .mapToInt(file -> paintSource(file, workspace, sourceDirectories,
+                                temporaryPaintedFilesDirectory, charset, log))
                         .sum();
 
                 if (count == paintedFiles.size()) {
@@ -412,6 +419,15 @@ public class SourceCodeFacade {
                         "Processing has been interrupted: skipping zipping of source files", workspace);
             }
 
+            try {
+                Files.delete(temporaryPaintedFilesDirectory);
+                log.logInfo("Deleted temporary painting directory %s", temporaryPaintedFilesDirectory);
+            }
+            catch (IOException exception) {
+                log.logException(exception, "Could not delete temporary painting directory %s",
+                        temporaryPaintedFilesDirectory);
+            }
+
             return log;
         }
 
@@ -419,6 +435,16 @@ public class SourceCodeFacade {
             return new CharsetValidation().getCharset(sourceCodeEncoding);
         }
 
+        private Path getTemporaryDirectory(final FilteredLog log) {
+            try {
+                return Files.createTempDirectory(directory);
+            }
+            catch (IOException exception) {
+                log.logException(exception, "Could not create temporary directory for painting");
+                return null;
+            }
+        }
+
         private Set<String> filterSourceDirectories(final File workspace, final FilteredLog log) {
             SourceDirectoryFilter filter = new SourceDirectoryFilter();
             return filter.getPermittedSourceDirectories(workspace.getAbsolutePath(),
@@ -426,22 +452,22 @@ public class SourceCodeFacade {
         }
 
         private int paintSource(final PaintedNode fileNode, final FilePath workspace,
-                final Set<String> sourceSearchDirectories, final Charset sourceEncoding, final FilteredLog log) {
+                final Set<String> sourceSearchDirectories, final Path temporaryPaintedFilesDirectory,
+                final Charset sourceEncoding, final FilteredLog log) {
             String relativePathIdentifier = fileNode.getNode().getPath();
             FilePath paintedFilesDirectory = workspace.child(directory);
             return findSourceFile(workspace, relativePathIdentifier, sourceSearchDirectories, log)
                     .map(resolvedPath -> paint(fileNode.getPaint(), relativePathIdentifier, resolvedPath,
-                            paintedFilesDirectory,
-                            sourceEncoding, log))
+                            paintedFilesDirectory, temporaryPaintedFilesDirectory, sourceEncoding, log))
                     .orElse(0);
         }
 
         private int paint(final CoveragePaint paint, final String relativePathIdentifier, final FilePath resolvedPath,
-                final FilePath paintedFilesDirectory, final Charset charset, final FilteredLog log) {
+                final FilePath paintedFilesDirectory, final Path paintedFilesFolder, final Charset charset,
+                final FilteredLog log) {
             String sanitizedFileName = sanitizeFilename(relativePathIdentifier);
             FilePath zipOutputPath = paintedFilesDirectory.child(sanitizedFileName + ZIP_FILE_EXTENSION);
             try {
-                Path paintedFilesFolder = Files.createTempDirectory(directory);
                 Path fullSourcePath = paintedFilesFolder.resolve(sanitizedFileName);
                 try (BufferedWriter output = Files.newBufferedWriter(fullSourcePath)) {
                     List<String> lines = Files.readAllLines(Paths.get(resolvedPath.getRemote()), charset);
@@ -452,6 +478,7 @@ public class SourceCodeFacade {
                     paint.setTotalLines(lines.size());
                 }
                 new FilePath(fullSourcePath.toFile()).zip(zipOutputPath);
+                Files.delete(fullSourcePath);
                 return 1;
             }
             catch (IOException | InterruptedException exception) {
```

This basically implements the aforementioned fix which uses one common temporary painting directory and performs the required cleanups.

As I am not really familiar with the code base, I did not open a PR for this yet. Additionally, corresponding tests to ensure the correct behaviour are still missing as well, mainly due to the same circumstances. Looking at the local testing instance and using some additional logging seems to indicate that the rendering is still correct, while the temporary directory will actually be removed at the end.

**Comment by fo-code** [comment]
Hello @stefan6419846 ,

thank you for reporting and also showing that solution, which helped a lot.
I created a PR with a fix for this issue.

I did not initially write the logic for code painting, but I guess it makes sense to create a unique temporary folder per file because of one corner case:
the names of the temporary painted code files are based on the Java package name together with the Java file name - these are the available information. But there can be a corner case, when there are multiple modules which use the same package structure. Due to the usage of a parallel stream here, this could be problematic since there could exist multiple files with the same name at the same time.
At least this is my understanding of it.

Maybe you can also try the new code of the PR in your environment to make sure it works and give me some feedback, even if i tried to recreate your use case and already tested it on my machine :)

**Comment by stefan6419846** [comment]
Thank you for your explanations on one versus multiple directories. One could still argue that the plugin could just use one common temporary directory per pipeline and generate the file-specific random directories inside this one, but this probably is a matter of taste and most likely only affects cases where something goes completely wrong with the plugin or its cleanup.

I just generated a corresponding snapshot from your branch and I am going to see if I manage to test this in the next few days on the actual system instead of a basic testing container.

Nevertheless, is there a chance that this desired cleanup behaviour will have a corresponding test case, so it will not break again in a future version?

**Comment by fo-code** [comment]
> Thank you for your explanations on one versus multiple directories. One could still argue that the plugin could just use one common temporary directory per pipeline and generate the file-specific random directories inside this one, but this probably is a matter of taste and most likely only affects cases where something goes completely wrong with the plugin or its cleanup.

I agree with that aspect regarding the fault safety and enhanced the PR based on your code snipped.

> Nevertheless, is there a chance that this desired cleanup behaviour will have a corresponding test case, so it will not break again in a future version?

I also added an additional assertion which checks that the files within the tmp directory are the same before and after the plugin execution.

> I just generated a corresponding snapshot from your branch and I am going to see if I manage to test this in the next few days on the actual system instead of a basic testing container.

Thank you, this would be great in order to test in different systems. Maybe you could take the new version which includes the enhancements I mentioned above?

**Comment by stefan6419846** [comment]
I just managed to actually test a recent snapshot of this on a real system and everything seemed to work correctly.

**Comment by uhafner** [comment]
Fixed in https://github.com/jenkinsci/code-coverage-api-plugin/releases/tag/v3.0.5
