### ISSUE TITLE
Pipeline support

### ISSUE THREAD

**Issue by IdanAdar** [jenkinsci/code-coverage-api-plugin#48]
You mention pipeline support, but I don't see any documentation regarding declarative pipelines or Nodejs-based projects...

**Comment by oleg-nenashev** [comment]
* Declarative pipelines use the same steps as scripted ones, so you can use the existing Pipeline examples there

Regarding Nodejs, you can publish coverage if they convert data to one of the standard formats. As alternative, coverage tools/plugins should get integration in downstream plugins. Code Coverage API is just an API plugin. Example: https://github.com/jenkinsci/llvm-cov-plugin

**Comment by cizezsy** [comment]
@IdanAdar Thanks for your issue :)

Regard the declarative pipeline, you can use Jenkins Snippet Generator to generate it. Also, I will add the documentation about pipelines in README later.

And about the Nodejs-based projects, if you mean the Nodejs coverage report support, we do not have it yet. But if you'd like to implement one, I am willing to give you my help :P
