### ISSUE TITLE
Additional details calling API

### ISSUE THREAD

**Issue by joshight** [jenkinsci/code-coverage-api-plugin#510]
Is there any additional documentation to help understand the api paths that can be used:

Coverage result: …​/{buildNumber}/coverage/…​/result/api/\{json|xml\}?depth={number}

I can't seem to determine the correct path to use here:

'https://{SERVER}/{ORG}/job/{FOLDER}/job/{PROJECT}/job/master/225/coverage/cobertura/result/api?depth=2'

**Comment by uhafner** [comment]
Can you please use #217 to add your requirements? There is no remote API in the moment.

What kind of data do you want to have listed?
