### ISSUE TITLE
Package or module specific coverage breakdown

### ISSUE THREAD

**Issue by stefan6419846** [jenkinsci/code-coverage-api-plugin#529]
Coverage is internally measured at different levels (module, package, file, etc.). Currently the results are rendered as overall result only. It would make sense to show a drill down of the results (tree maps, files tables) per module or package.

**Comment by uhafner** [comment]
Can you please elaborate what breakdown you are expecting here? The tree views already show results by package. The files table shows the files by package as well? How is this related to #761?

**Comment by stefan6419846** [comment]
I am looking for some more general overview on the package/directory levels, basically some sort of table as for the files, but with the results aggregated as in the "Line Coverage" and "Branch Coverage" heat maps. The goal is to quickly query for directories with good and bad coverage without having to "interpret" the different shades from the heat maps, where especially for large projects with lots of sub-packages, navigating can quickly become quite complex. Doing this in the current "Files" table requires aggregating the different values manually.

As you can see from the reporting times, #529 is much older than #761, thus rather unrelated. I mostly consider #761 a general display issue/bug report, while #529 rather is a feature request for a new display type. When #529 has been reported, #761 has not yet been an issue as the old "Files" table always provided the full package names, even for the usual 24" displays the corresponding Jenkins instance is mostly accessed with by the users.
