### ISSUE TITLE
Strange ordering for total coverage overview

### ISSUE THREAD

**Issue by stefan6419846** [jenkinsci/code-coverage-api-plugin#530]
### What feature do you want to see added?

The "Total coverage overview" graph appears to use some quite strange order:

1. Directory
2. Branch
3. Line
4. File

From a logical point of view, it would make much more sense to reorder them (where the order for branch and line coverage might be interchangeable):

1. Directory
2. File
3. Line
4. Branch

**Comment by uhafner** [comment]
Can you please provide a screenshot? In the screenshot in https://github.com/jenkinsci/code-coverage-api-plugin#features the order of the elements is using the expected order. 

The ordering (at least in the next major release) is determined by the order of the enum https://github.com/uhafner/coverage-model/blob/main/src/main/java/edu/hm/hafner/metric/Metric.java

**Comment by stefan6419846** [comment]
This is what I see at the moment (plugin version 3.4.0):

![Total coverage overview](https://user-images.githubusercontent.com/96178532/207263737-fa6413ee-74dd-4ae2-9433-a6c7440fc5bf.png)

**Comment by stefan6419846** [comment]
Judging from the pipeline using `publishCoverage adapters: [istanbulCobertura('coverage.xml')]`, I assume that this is the Istanbul adapter for a project using *coverage.py* to determine the coverage itself.

**Comment by uhafner** [comment]
Yes, the result is currently read by https://github.com/jenkinsci/code-coverage-api-plugin/blob/master/plugin/src/main/java/io/jenkins/plugins/coverage/adapter/IstanbulCoberturaReportAdapter.java

Do you have a example result file that you are allowed to share as part of our unit test suite? Then I can check, if everything still works as expected with the new parsers in https://github.com/uhafner/coverage-model

**Comment by stefan6419846** [comment]
I have generated a fictional result file based upon the structure of a real one, which is suitable for publishing here: [coverage.xml](https://github.com/jenkinsci/code-coverage-api-plugin/files/10218409/coverage.xml.txt)

**Comment by stefan6419846** [comment]
This seems to be fixed now.
