### ISSUE TITLE
Code Coverage API

### ISSUE THREAD

**Issue by AnjaleeJung52** [jenkinsci/code-coverage-api-plugin#536]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins

### Reproduction steps

.

### Expected Results

To install the plugin Code Coverage API but couldnt 

### Actual Results

Unable to install the plugin mentioned above

### Anything else?

.

**Comment by uhafner** [comment]
Please add meaningful details when creating an issue.
