### ISSUE TITLE
Add a threshold for the `failBuildIfCoverageDecreasedInChangeRequest` parameter

### ISSUE THREAD

**Issue by xbombev** [jenkinsci/code-coverage-api-plugin#543]
### What feature do you want to see added?

Currently the `failBuildIfCoverageDecreasedInChangeRequest` parameter allows to mark a build job as failed when the Coverage has decreased when compared to the target branch. However when you enable it and you make a change request, sometimes the build job fails with a ridiculous reason, here is an example:

`io.jenkins.plugins.coverage.exception.CoverageException: Fail build because this change request decreases line coverage by -0.679924`. 

There should be a way to determine a threshold beyond which the build should be marked as `FAILED`. Currently there isn't and we get randomly failed builds, because the line coverage dropped by, for example `0.0005' in one of the build re-runs.

So please consider adding such a threshold or modify the plugin to not fail on such ridiculous values, for example `if coverage dropped by more then 1 -> FAILED".

**Comment by uhafner** [comment]
This will be part of https://github.com/jenkinsci/code-coverage-api-plugin/pull/512. This PR will introduce quality gates that work on overall and delta results.
