### ISSUE TITLE
Multibranch support

### ISSUE THREAD

**Issue by IdanAdar** [jenkinsci/code-coverage-api-plugin#55]
Hi,

We're using the Multibranch pipeline type in our Jenkins setup for our Node.js-based projects.
In these projects we use the mocha-jenkins plugin which generates the lcov report.

So, we have the lcov data, but in multibranch pipeline there is no UI option as mentioned in step 6: 

```
6. (Optional) Specify Source code storing level to enable source code navigation.
```

How would I set the threshold for failing builds if not met
Is it possible to set these options in the pipeline code instead?

Also, for Node.js-based projects what would I need to place here instead of `jacoco`?

```
publishCoverage adapters: [jacocoAdapter('target/site/jacoco/jacoco.xml')]
```

**Comment by IdanAdar** [comment]
jenkins-mocha in GitHub: https://github.com/stjohnjohnson/jenkins-mocha#readme

**Comment by cizezsy** [comment]
@IdanAdar OK, thanks~

**Comment by cizezsy** [comment]
Hi @IdanAdar, jenkins-mocha can use cobertura reporter to produced coverage report. I have add support for the cobertura reporter in version 1.0.6 ( #62 ). 

```
{
    "scripts": {
        "devtest": "jenkins-mocha --cobertura test/*"
    }
}
```

You can use Istanbul Cobertura Adapter to collect coverage reports now :P
