### ISSUE TITLE
Merging multiple reports

### ISSUE THREAD

**Issue by mfuchs** [jenkinsci/code-coverage-api-plugin#56]
Hi,
I collect code coverage in different pipeline steps.
Once with unit tests and once with ui-tests.
For simplicity the resulting JaCoCo files are called coverage1.xml and coverage2.xml.

I was unable to merge the coverage results.
I tried things like:

    publishCoverage adapters: [jacocoAdapter("coverage1.xml")], sourceFileResolver: sourceFiles('STORE_ALL_BUILD'), tag: 'foo' 
    publishCoverage adapters: [jacocoAdapter("coverage2.xml")], sourceFileResolver: sourceFiles('STORE_ALL_BUILD'), tag: 'foo' 

and also

    publishCoverage adapters: [jacocoAdapter("coverage*.xml")], sourceFileResolver: sourceFiles('STORE_ALL_BUILD')

Yet there are still two reports listed and the overall coverage is both results added divded by two.
Though what I really want is an overall coverage, i.e. all lines covered by either of the two.

Is there a way to do that?

**Comment by cizezsy** [comment]
@mfuchs Thanks for the feedback, I will look at it :p

**Comment by Victoremepunto** [comment]
Hi,

I've collected two different reports ( from two separate test suits - unit and int tests ) and used the coverage plugin from the project ( using JaCoCo in a Spring Boot project with Gradle ) to merge both reports into the same XML report, which I feed to Code Coverate API plugin. 

as an example, in my Gradle config: 

```
jacocoTestReport {

    reports {
        xml.enabled true
    }

    executionData = project.fileTree(dir: '.', include:'**/build/jacoco/*.exec')
}
```
This way I collect all the *.exec files generated by JaCoCo into single xml file.

Perhaps you can try the same while Code Coverage API plugin supports this.

Hope it helps !

**Comment by uhafner** [comment]
See #161
