### ISSUE TITLE
net/sf/saxon/TransformerFactoryImpl has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by irishuahua** [jenkinsci/code-coverage-api-plugin#573]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

Jenkins：2.346.3
jdk：1.8.0_251
code-coverage-api-plugin：3.5.0
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

centos：3.10.0-1127.el7.x86_64

### Reproduction steps

run my pipeline

### Expected Results

success

### Actual Results

net/sf/saxon/TransformerFactoryImpl has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
17:26:25  <Thread 295, name: 'Running CpsFlowExecution[Owner[DASHBOARD/DASHBOARD/backend/gc-dataprocess-dev_preCheck_apitest_new/2929:DASHBOARD/DASHBOARD/backend/gc-dataprocess-dev_preCheck_apitest_new #2929]]'>
17:26:25  java.lang.UnsupportedClassVersionError: net/sf/saxon/TransformerFactoryImpl has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
17:26:25      at java.lang.ClassLoader.defineClass1() [ClassLoader.java:-2]
17:26:25      at java.lang.ClassLoader.defineClass() [ClassLoader.java:756]
17:26:25      at org.apache.tools.ant.AntClassLoader.defineClassFromData() [AntClassLoader.java:1172]
17:26:25      at org.apache.tools.ant.AntClassLoader.getClassFromStream() [AntClassLoader.java:1340]
17:26:25      at org.apache.tools.ant.AntClassLoader.findClassInComponents() [AntClassLoader.java:1392]
17:26:25      at org.apache.tools.ant.AntClassLoader.findClass() [AntClassLoader.java:1357]
17:26:25      at org.apache.tools.ant.AntClassLoader.loadClass() [AntClassLoader.java:1112]
17:26:25      at java.lang.ClassLoader.loadClass() [ClassLoader.java:351]
17:26:25      at io.jenkins.plugins.coverage.adapter.XMLCoverageReportAdapter.convert() [XMLCoverageReportAdapter.java:44]
17:26:25      at io.jenkins.plugins.coverage.adapter.CoverageReportAdapter.getResult() [CoverageReportAdapter.java:57]
17:26:25      at io.jenkins.plugins.coverage.CoverageProcessor.convertToResults() [CoverageProcessor.java:364]
17:26:25      at io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport() [CoverageProcessor.java:114]
17:26:25      at io.jenkins.plugins.coverage.CoveragePublisher.perform() [CoveragePublisher.java:116]
17:26:25      at jenkins.tasks.SimpleBuildStep.perform() [SimpleBuildStep.java:123]
17:26:25      at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run() [CoreStep.java:101]
17:26:25      at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run() [CoreStep.java:71]
17:26:25      at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0() [SynchronousNonBlockingStepExecution.java:47]
17:26:25      at java.util.concurrent.Executors$RunnableAdapter.call() [Executors.java:511]
17:26:25      at java.util.concurrent.FutureTask.run() [FutureTask.java:266]
17:26:25      at java.util.concurrent.ThreadPoolExecutor.runWorker() [ThreadPoolExecutor.java:1149]
17:26:25      at java.util.concurrent.ThreadPoolExecutor$Worker.run() [ThreadPoolExecutor.java:624]
17:26:25      at java.lang.Thread.run() [Thread.java:748]

### Anything else?

when I use 1.4.0 for code-coverage-api-plugin，it is ok，what is the problem?

**Comment by uhafner** [comment]
Please upgrade your Jenkins to Java 11 and Jenkins 1.387.1.

Please also install:
https://github.com/jenkinsci/code-coverage-api-plugin/releases/tag/v4.0.0
