### ISSUE TITLE
Support scala scoverage report

### ISSUE THREAD

**Issue by LorenzMende** [jenkinsci/code-coverage-api-plugin#588]
### What feature do you want to see added?

We are working with [scoverage](https://github.com/scoverage) for creating coverage data for scala.
I would like to extend this jenkins plugin to support the given coverage type.

Which files should need to be updated/ created for this extension? I already had a look at the coverage-model repo but was not yet able to identify how they work together.

Goal would be to extend this plugin, so that scoverage reports can be ingested, statement and branch coverage are reported/ recognized correctly

PS: I know that scoverage supports the cobertura report type, but to my knowledge only poorly - missing condition coverage, leading to unrecognized branch coverage and only limited to line coverage.

**Comment by uhafner** [comment]
New coverage parsers should be added in the https://github.com/uhafner/coverage-model project first. Once they are there, we can register and use them here in the Jenkins plugin. 

Here are the three parsers:
https://github.com/uhafner/coverage-model/tree/main/src/main/java/edu/hm/hafner/coverage/parser
