### ISSUE TITLE
Enum name/value definitions counted as uncovered methods

### ISSUE THREAD

**Issue by aboe026** [jenkinsci/code-coverage-api-plugin#598]
### Jenkins and plugins versions report

Jenkins: 2.387.1
OS: Linux - 4.19.104-microsoft-standard
Java: 11.0.18 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
code-coverage-api:4.0.2
### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 11 Pro (10.0.22621), but Jenkins is running in docker container based off of `jenkins/jenkins:2.387.1-lts`

### Reproduction steps

1. Configure Jenkins instance with this repo: https://github.com/aboe026/jenkins-shared-library/blob/main/Jenkinsfile
2. Run build for the repo in Jenkins

### Expected Results

The "Overview" tab on the coverage page should show full coverage for the "Method" category

### Actual Results

The "Overview" tab on the coverage page shows there are 20 lines uncovered:
![code-coverage-api-overview](https://user-images.githubusercontent.com/11340779/227817265-7a715b2c-e160-4736-8306-c48391eba06a.png)
At first I had no idea what methods would be listed as uncovered, because my local jacoco report shows all methods are covered:
![jacoco-coverage](https://user-images.githubusercontent.com/11340779/227817544-c1a976a6-8242-42b3-9945-97470f70de83.png)

Then I realized that the number 20 (of uncovered methods) equals the number of "methods" that I have defined for enum name/values, like:

```groovy
enum CodeCoverageCategory {

    BRANCH('branch'),
    CLASS('class'),
    FILE('file'),
    INSTRUCTION('instruction'),
    LINE('line'),
    METHOD('method'),
    MODULE('module'),
    PACKAGE('package')

    final String value

    private CodeCoverageCategory(String value) {
        this.value = value
    }

    @Override
    @NonCPS
    String toString() {
        return this.value
    }

}
```

I'm not sure why the code coverage api plugin is listing such methods as uncovered, when I have unit tests utilizing those enums, and my local jacoco reporter says those methods are covered.

### Anything else?

Might also be nice for the code coverage api plugin to have links or somehow show what the missed methods are, because I was only able to figure out what they were by induction/guessing.

**Comment by uhafner** [comment]
Seems that I did not manage it to run your Jenkinsfile on my installation. Can you attach the jacoco.xml file please? Then I can create a simple test case.

**Comment by aboe026** [comment]
I've attached a zip containing a few different files. The `local-machine` is the contents of my `build\reports\jacoco\test` directory in my repository on my local machine after I ran `./gradlew test && ./gradlew jacocoTestReport` on the latest code for https://github.com/aboe026/jenkins-shared-library. The `previous-jenkins-build` contains jacoco files from the working directory of a previous build (When I was using the `jacoco` step to save coverage on builds instead of the `recordCoverage` step) of the https://github.com/aboe026/jenkins-shared-library from my Jenkins docker container:
[jacoco-results.zip](https://github.com/jenkinsci/code-coverage-api-plugin/files/11095291/jacoco-results.zip)
Let me know if there's anything else I can grab!

**Comment by uhafner** [comment]
> Might also be nice for the code coverage api plugin to have links or somehow show what the missed methods are, because I was only able to figure out what they were by induction/guessing.

Please create a new issue so this will not be forgotten. It would be also helpful, if you can add some ideas where and how this information should be shown.
