### ISSUE TITLE
Cannot find source files for Node.JS repo with multiple source directories

### ISSUE THREAD

**Issue by aboe026** [jenkinsci/code-coverage-api-plugin#599]
### Jenkins and plugins versions report

Jenkins: 2.387.1
OS: Linux - 4.19.104-microsoft-standard
Java: 11.0.18 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)

code-coverage-api:4.0.2

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 11 Pro (10.0.22621), but Jenkins is running in docker container based off of `jenkins/jenkins:2.387.1-lts`

### Reproduction steps

1. Have a repository with multiple "source" directories (such as a monorepo with `lib` and `services` directories)
2. Run a Jenkins build with the repository and the code coverage api plugin

### Expected Results

All source code files would be found correctly

### Actual Results

It seems to find the first source code file (`libs/env/src/env.ts`) fine:
![code-coverage-api-files](https://user-images.githubusercontent.com/11340779/227818060-22f1756a-50b0-4777-9fb6-2bcc3881123e.png)

but then it seems to prepend the subdirectory of that first file (`libs/env/src`) when it tries to find all other source files, even though those other source files are in a different sub-directory (`services/api/src` and `services/ui/src`):
```
[Cobertura] Successfully processed file 'coverage/cobertura-coverage.xml'
[Coverage] [-ERROR-] Errors during source code painting:
[Coverage] [-ERROR-] Errors during source code painting:
[Coverage] [-ERROR-] Errors during source code painting:
[Coverage] [-ERROR-] Errors during source code painting:
[Coverage] [-ERROR-] Errors during source code painting:
[Coverage] [-ERROR-] Source file 'libs/env/src/services/api/src/graphql/resolver.ts' not found
[Coverage] [-ERROR-] Source file 'libs/env/src/services/api/src/app-info.ts' not found
[Coverage] [-ERROR-] Source file 'libs/env/src/services/api/src/database/store.ts' not found
[Coverage] [-ERROR-] Source file 'libs/env/src/services/ui/libs/client/src/util/error-util.ts' not found
[Coverage] [-ERROR-] Source file 'libs/env/src/services/api/src/api.ts' not found
[Coverage] [-ERROR-] Source file 'libs/env/src/services/ui/src/env.ts' not found
[Coverage] [-ERROR-] Source file 'libs/env/src/services/api/src/database/movie-store.ts' not found
[Coverage] Obtaining action of reference build
[Coverage] Reference build recorder is not configured
[Coverage] -> No reference build defined, falling back to previous build: '0.1.0+21'
[Coverage] -> Found reference result in build '0.1.0+21'
[Coverage] Calculating the code delta...
[Coverage] -> No delta calculator installed yet. You need to install the 'git-forensics' plugin to enable it for Git.
[Coverage] Calculating coverage deltas...
[Coverage] No quality gates have been set - skipping
[Coverage] Executing source code painting...
[Coverage] Painting 12 source files on agent
[Coverage] Searching for source code files in '/var/jenkins_home/workspace/imdb-songs_imdb-songs_PR-14/PR-14-22/src/main/java'
[Coverage] -> finished painting (1 files have been painted, 11 files failed)
```

### Anything else?

I'm also seeing output related to `src/main/java` as a source directory, seems like that should be configurable (to be more compatible with non-Java, i.e. Node.JS, projects)

**Comment by uhafner** [comment]
Which recorder step did you select? The new one [recordCoverage](https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#recordcoverage-record-code-coverage-results), or the old one [publishCoverage](https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#publishcoverage-publish-coverage-report-deprecated)?

Which directories did you specify in the step?

![Bildschirm­foto 2023-03-27 um 08 46 33](https://user-images.githubusercontent.com/503338/227861957-2a440074-8e2e-4d03-acc4-607a04ff3b3b.png)

Can you please attach an example xml report?

**Comment by aboe026** [comment]
Looks to be the new one:
```groovy
recordCoverage(
    skipPublishingChecks: true,
    sourceCodeRetention: 'EVERY_BUILD',
    tools: [
        [
            parser: 'COBERTURA',
            pattern: 'coverage/cobertura-coverage.xml'
        ]
    ]
)
```
I didn't specify any `sourceDirectories` because it seemed like it was pre-pending the source code file path with it, but the source code paths in the `coverage.xml` are all relative to the working directory, so adding any `sourceDirectories` just made the lookup fail because the paths were getting repeated. I've attached both the `coverage.xml` from the working directory of the Jenkins build, as well as the `coverage-sources/coverage/cobertura-coverage.xml` since I'm not sure which one is used by the code-coverage-api-plugin:
[coverage.zip](https://github.com/jenkinsci/code-coverage-api-plugin/files/11083882/coverage.zip)

**Comment by viceice** [comment]
probably this line is the cause?
https://github.com/jenkinsci/code-coverage-api-plugin/blob/232fc3d6fe803c9ca43c4304876cf6c88624784c/plugin/src/main/java/io/jenkins/plugins/coverage/CoveragePublisher.java#L140

**Comment by viceice** [comment]
so it causes to go to second condition instead of the first
https://github.com/jenkinsci/code-coverage-api-plugin/blob/232fc3d6fe803c9ca43c4304876cf6c88624784c/plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/SourceCodePainter.java#L164-L173

**Comment by uhafner** [comment]
> so it causes to go to second condition instead of the first
> 
> https://github.com/jenkinsci/code-coverage-api-plugin/blob/232fc3d6fe803c9ca43c4304876cf6c88624784c/plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/SourceCodePainter.java#L164-L173

Actually this is only a logging statement. And that one is broken, indeed. The source code scanner correctly uses the root of the workspace as well, see https://github.com/jenkinsci/code-coverage-api-plugin/blob/232fc3d6fe803c9ca43c4304876cf6c88624784c/plugin/src/main/java/io/jenkins/plugins/coverage/metrics/source/SourceCodePainter.java#L259-L274

**Comment by uhafner** [comment]
Does it work for you as well? Your case looked a little bit different.

**Comment by aboe026** [comment]
Looks like the 4.0.3 version of the plugin fixes it for me, thanks for the lightning fast turnaround @uhafner!!!

**Comment by viceice** [comment]
Works for me, will open a new issue for my missing files
