### ISSUE TITLE
Different branch coverage between dotnet test and code coverage

### ISSUE THREAD

**Issue by LordSaitamaa** [jenkinsci/code-coverage-api-plugin#625]
### Jenkins and plugins versions report

Code Coverage API Version 4.0.3
Jenkins Version 2.395

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

1. Execute dotnet test --no-build -c "Release" -e:ExcludeByFile="**/Properties/*.cs" -e:CollectCoverage=true -e:CoverletOutput="../TestResults/" -e:CoverletOutputFormat="cobertura" 
2. Run a jenkins build in which the following instruction is used: recordCoverage(tools: [[parser: 'COBERTURA', pattern: 'TestResults/Cobertura.xml']], id: 'COBERTURA', name: 'Cobertura Coverage', sourceCodeRetention: 'NEVER', checksAnnotationScope: "SKIP", failOnError: true)

### Expected Results

The Coverage between the cobertura outputfile (dotnet test + coverlet plugin) and the recorded coverage by the code coverage jenkins plugin is different

Reported Coverage by coverlet:
![coverage1](https://user-images.githubusercontent.com/64631439/230109867-695d2e99-5e5d-4fd5-ac8d-64beb0463d2d.png)

Reported Coverage by code-coverage-api-plugin
![coverage2](https://user-images.githubusercontent.com/64631439/230110004-19927883-105a-42dd-ab2b-8c4647b1d2bc.png)

### Actual Results

Both coverage tools deliver the same coverage information

### Anything else?

I've seen that 11 branch coverage cases are missed but cant say the exact reason wyh they're missed because there are nearly 0 information about it

**Comment by uhafner** [comment]
Can you please attach the "cobertura.xml" if possible? You can see the missing branches in the source view (or in the file table).

**Comment by LordSaitamaa** [comment]
Sure: (sorry xml isnt supported for file uploads)
[cobertura.txt](https://github.com/jenkinsci/code-coverage-api-plugin/files/11167004/cobertura.txt)
