### ISSUE TITLE
Jenkins version requirements too high

### ISSUE THREAD

**Issue by truebit** [jenkinsci/code-coverage-api-plugin#64]
It's very good to know such plugin providing an API. But the "Minimum Jenkins requirement" is  v2.60.3.

Could you make this plugin to be a little widely supported? We have v2.46 in use, upgrading is nearly impossible. Is there really some methods or class needed in jenkins core v2.60.3?

**Comment by cizezsy** [comment]
@truebit Thanks for your feedback :)

This plugin uses Java 8 now and cannot run on JVM which version below 8. Jenkins 2.60.1 is the first LTS release to require Java 8, so we need it as the minimum Jenkins version.

@oleg-nenashev Is there any method to lower the Jenkins requirement version without changing the Java version?

**Comment by cizezsy** [comment]
@truebit I have made some changes in the branch [feat/support-low-version-jenkins](https://github.com/jenkinsci/code-coverage-api-plugin/tree/feat/support-low-version-jenkins).

If you want, you can test it by the fellow steps:
1. Clone the codes and switch to branch `feat/support-low-version-jenkins`
2. Run `mvn package`
3. Install the generated file `code-coverage-api.hpi` on `PluginManager -> Advanced` page

Once I found there is no compatibility issue, I will merge the branch and release it.

**Comment by truebit** [comment]
Ha, I just did the same and completed build on my own. I am now trying to figure out how to write pipeline using this plugin
IMHO, you should find the least support version instead of my version here to add more compatability:)

**Comment by cizezsy** [comment]
@truebit You can use Jenkins Snippet Generator to generate the pipeline step :P

Yeah, I will look at it and find a proper version :) Thanks~

**Comment by truebit** [comment]
It seems default jacoco plugin would generate the report directly but no jacoco.xml report found in workspace. Do you know why?

**Comment by cizezsy** [comment]
@truebit 

You can config jacoco plugin to generate xml report by using the fellowing configuration :P

```xml
<build>
    <plugins>
        <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <version>0.8.1</version>
            <executions>
                <execution>
                    <goals>
                        <goal>prepare-agent</goal>
                    </goals>
                </execution>
                <execution>
                    <id>report</id>
                    <phase>package</phase>
                    <goals>
                        <goal>report</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by truebit** [comment]
we use on the fly mode, a.k.a using `-javaagent` injection to dump exec file; then jacoco plugin would generate a report directly without xml file...

**Comment by cizezsy** [comment]
@truebit You can use [JaCoCo CLI](https://www.jacoco.org/jacoco/trunk/doc/cli.html) to generate xml format report from `.exec`(By using the report sub-command).

Also, regard Jenkins version requirement, I have asked for advice from Jenkins yesterday:
> the problem is that users of Java 7 and old Jenkins versions will be also able to install the plugin, and  the instance may blow up. We introduced Java compatibility checks in weekly releases 2 weeks ago,  but there is no protection in old cores

So I won't lower the Jenkins version requirement and release it :( 

But, I will maintain the low-jenkins-version branch and keep it up to date with the dev branch. If you want to use this plugin in lower version, you can clone and build it yourself. Sorry for the inconvience.
