### ISSUE TITLE
resettable quality gates

### ISSUE THREAD

**Issue by theKBro** [jenkinsci/code-coverage-api-plugin#644]
### What feature do you want to see added?

Resettable quality gates for coverage results with `baseline: 'PROJECT_DELTA'

Till now we use it with `threshold: 0.0` but sometimes the build just gets unstable without changes in coverage. Or did I misconfigure this? Hence the threshold docu for the different baselines is pretty short.

**Comment by uhafner** [comment]
What do you mean with resettable?

**Comment by theKBro** [comment]
With resettable I mean the same as available for `recordIssues`.
Type NEW instead of TOTAL_ERROR
` qualityGates: [
      [threshold: 1, type: 'TOTAL_ERROR', unstable: true],
      [threshold: 1, type: 'NEW', unstable: true]
    ],`
where the quality gate can be resetted
![image](https://user-images.githubusercontent.com/14205420/232075157-34efb3c2-f250-4862-83c8-5a2b91ea8648.png)

Is there already a similar configuration for `recordCoverage` qualityGates?

**Comment by uhafner** [comment]
But in the warnings plugin this simply changes the reference build so that warnings that are new in build x are still counted as new in build x + 1. This is not required in the coverage plugin where you compare a percentage in every build.

**Comment by theKBro** [comment]
So the coverage reference build is always the previous build and not the last stable build? Then i totally missunderstood this.
So with `baseline: 'PROJECT_DELTA` only the build where the coverage decreases is marked unstable the following build witout any changes but still with a lower coverage than the previous succesfull build will be marked as success?

**Comment by theKBro** [comment]
I just don't want the coverage to decrease

Build1: 75 % -> success
Build2: 73 % -> failure
Build3: 73 % -> failure
Build4: 76 % -> success
Build5: 75 % -> failure => reset quality gate
Build6: 75 % -> success

Is there no way to achieve this?

**Comment by uhafner** [comment]
> So the coverage reference build is always the previous build and not the last stable build?

The reference build is computed with an extra step: https://github.com/jenkinsci/git-forensics-plugin#reference-build

I did not implement something similar to the warnings plugin. So the use case your are looking for is not supported here.

**Comment by theKBro** [comment]
Ok so you don't think that would be a useful feature?

**Comment by uhafner** [comment]
Well, that depends on your development process.

I would not use such an approach in my projects anymore: Typically projects change by merging pull requests into the baseline. So in this case the coverage plugin must measure the delta between the PR head and the merge target head. Here I would apply quality gates. But using quality gates in the master from build to build is not useful in such an approach (its too late)...

**Comment by theKBro** [comment]
Ok, again we are screwed because we stick to svn.
