### ISSUE TITLE
Support for SonarQube Generic Coverage Report

### ISSUE THREAD

**Issue by andre2007** [jenkinsci/code-coverage-api-plugin#65]
SonarQube defines a generic coverage report format:
https://docs.sonarqube.org/latest/analysis/generic-test/

Could this format be supported?

**Comment by cizezsy** [comment]
@andre2007 This format seems not hard to implement, I will add it in the future :)

**Comment by andre2007** [comment]
@cizezsy Did you already had time to look at this?

**Comment by cizezsy** [comment]
@andre2007 OK, I will write a new plugin to support it in this month :)

**Comment by cizezsy** [comment]
@andre2007 really sorry for the delay, I am too busy in last month :(

SonarQube generic coverage plugin: https://github.com/cizezsy/sonarqube-generic-coverage-plugin/tree/master.

I will open a Plugin Hosting Request so that you can use it in Jenkins update center.

**Comment by cizezsy** [comment]
Link to Hosting Request: https://issues.jenkins-ci.org/browse/HOSTING-801

**Comment by andre2007** [comment]
Thanks a lot!

**Comment by cizezsy** [comment]
Released 1.0 version.
