### ISSUE TITLE
How to configuration the references build?

### ISSUE THREAD

**Issue by nhannguyentrong** [jenkinsci/code-coverage-api-plugin#663]
### Describe your use-case which is not covered by existing documentation.

I get the warning on the console log when using code coverage api plugin on jenkins

```
[Coverage] Obtaining action of reference build
[Coverage] Reference build recorder is not configured
[Coverage] -> No reference build defined, falling back to previous build: '#12'
[Coverage] -> Found reference result in build '#12'
[Coverage] Calculating the code delta...
````
I want to configure the reference build to the specified build do not mention in the document.

**Comment by uhafner** [comment]
Please have a look here: https://github.com/jenkinsci/git-forensics-plugin#reference-build

Is this sufficient? Feel free to provide a PR that links this reference in the README.
