### ISSUE TITLE
File coverage list contents disappears after viewing a file, yet in an incognito browser (or clearing site data) we can see them

### ISSUE THREAD

**Issue by lorenh** [jenkinsci/code-coverage-api-plugin#688]
### Jenkins and plugins versions report

we are using the code coverage plugin version 4.6.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows controller and agent.

### Reproduction steps

1. Execute a job that publishes a cobertura coverage report. Everything in the published report looks great, the files list is fully populated.
2. Click on a file to view the contents.
3. Press the browser back button to return to the files list and it is completely empty. Nothing you can do seems to bring the files back. (It appears to be some sort of cookie or session)

4. Open a new Incognito browser and log into Jenkins and navigate to the same job and the file coverage list is fully populated again (that is, until you view a file and back out in which case the incognito browser is also now broken)

### Expected Results

I expect the list of files to remain populated.

### Actual Results

List of files becomes empty.  One of our users reported that clearing browser site data also made the list return again.

**Comment by uhafner** [comment]
Do you see any messages in the console log of your browser? 
Which browser are you using?
Do other team members have the same problem with your instance?
Does the same problem appear in our CI instance as well with your browser?
https://ci.jenkins.io/job/Plugins/job/coverage-model/job/main/33/coverage/

**Comment by uhafner** [comment]
I see. I think the problem can be the broken serialization of the table state due to Jenkins internal prototype.js library. 

Can you try to deactivate Prototype.js (see https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins) and try again? 

A different test (with enabled Prototype) would be:

1. Open the coverage files tab
2. Open a source file from there
3. Clear the browser local storage for the Jenkins site (Chrome developer tools->Application->Local Storage->Your Jenkins URL
4. Press Back in your browser

When this works but the same without 3. does not work, then we identified the problem.

**Comment by lorenh** [comment]
We are running 2.405, where prototype was supposed to be disabled by default, and indeed when I went to my user config experiments as referenced in the article it was already disabled.  So disabling prototype seems to have no effect. It is still throwing the error.

Your second proposed experiment does work.

  1.  Open the coverage files tab
  2.  Open a source file from there
  3.  Clear the browser local storage for the Jenkins site (Chrome developer tools->Application->Local Storage->Your Jenkins URL
  4.  Press Back in your browser - FILES WERE POPULATED!

And when I repeat this but skip step 3 files were not populated and earlier reported errors existed in console. (Note: this is with prototype disabled... which it was by default)
________________________________

**Comment by uhafner** [comment]
I see. Then it is broken even without Prototype. Can you please copy the value of the table configuration JSON from the local storage? It is similar to `DataTables_absolute-coverage-table-inline_/job/coverage-model-history/17/coverage/`? Then I can try to reproduce these values in my instance...

**Comment by uhafner** [comment]
It would be helpful if someone could post the content of the value.

**Comment by uhafner** [comment]
> {
>   "time": 1686907873655,
>   "start": 0,
>   "length": 10,
>   "order": "[[\"1\", \"asc\"]]",
>   "search": {
>     "search": "",
>     "smart": true,
>     "regex": false,
>     "caseInsensitive": true
>   },

@meiswjn: it looks like you did *not* disable Prototype.js. 

Without Prototype this section looks like:

```
"order":[[1,"asc"]]
```

**Comment by meiswjn** [comment]
If I see it correctly, disabling Prototype JS is only possible with Jenkins >2.404. We are sadly bound to LTS for now. @lorenh are you able to test it with 2.404?

**Comment by uhafner** [comment]
@meiswjn  Which version of the data-tables plugin are you using? In https://github.com/jenkinsci/data-tables-api-plugin/pull/360/files I disabled the saving of the JSON properties if Prototype.js is enabled.

**Comment by meiswjn** [comment]
Nice, that fixes the issue I think!

**Comment by uhafner** [comment]
Please reopen if that does not help. Note that the next Jenkins LTS will have no Prototype anymore.
