### ISSUE TITLE
Report should be searchable/filterable/sortable

### ISSUE THREAD

**Issue by alclonky** [jenkinsci/code-coverage-api-plugin#71]
The package name should be searchable by browser search function.
Right now you have to search by hand in a long unsorted list.

**Comment by sll552** [comment]
This would be a really nice addition for projects with a large number of components 👍

**Comment by cizezsy** [comment]
@alclonky @sll552 Thanks very much for your feedback~ The report is sorted now, you can try it in version 1.0.9 :) 

The current method of drawing chart is not very easy to make the name searchable, I will try to fix it in the future.

**Comment by alclonky** [comment]
Thanks, that helps for now
