### ISSUE TITLE
Charts not shown anymore in Jenkins

### ISSUE THREAD

**Issue by christophweser** [jenkinsci/code-coverage-api-plugin#714]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Tried on Win 10 and Win 11 on Edge and Chrome. All with same result.

Jenkins Version 2.410
Code Coverage API Plugin Version 4.7.0

### Reproduction steps

Step 1: Just open Jacoco code coverage in Jenkins.

### Expected Results

See charts

### Actual Results

Only see line coverage but no further chars. See image
Everywhere it's marked red the charts are not working.

![Screenshot 2023-06-20 083343](https://github.com/jenkinsci/code-coverage-api-plugin/assets/65313217/60adcbed-bb00-4d31-96bb-2eb9f5837ef7)

### Anything else?

Any help is highly appreciated.

(Of course tried restarting server and cleaning browser caches.)

**Comment by uhafner** [comment]
From the color of the charts it looks like you are still using the old and deprecated step. Please upgrade to the latest step to get all new features. The old step is not supported anymore.

**Comment by christophweser** [comment]
Hello,

highly appreciate your fast reply.

What do you mean by "step"?
I'm using the latest available Jenkins version and the latest available Plugin?

Thanks,
Christoph

**Comment by uhafner** [comment]
Step is the basic unit of work in Jenkins, see

- https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#recordcoverage-record-code-coverage-results
- https://github.com/jenkinsci/code-coverage-api-plugin#freestyle-project
- https://github.com/jenkinsci/code-coverage-api-plugin#pipeline-example

**Comment by christophweser** [comment]
I wish I had noticed the yellow part earlier to then get the idea looking for a new post build action by myself.
That would have saved you some time you spent in my.

![image](https://github.com/jenkinsci/code-coverage-api-plugin/assets/65313217/4f0aa4fd-ff39-49b8-84bd-860755f5df13)


Thanks a lot for your help.
