### ISSUE TITLE
Add support for empty results

### ISSUE THREAD

**Issue by enys** [jenkinsci/code-coverage-api-plugin#723]
The coverage step should add support for empty results:

1. when there are no input files found
2. when there is no coverage information in an existing file

It makes sense to re-use the existing property `failOnError` for both cases, see https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#recordcoverage-record-code-coverage-results.  

In both cases a new UI needs to be designed that takes care of such an edge case.

Note that the second requirement needs to be implemented in the https://github.com/jenkinsci/coverage-model library.

**Comment by uhafner** [comment]
Can you please clarify your requirement? Which one are you interested in:

- The plugin should not report an error when there are no input files found?
- The plugin should not report an error when there is no coverage information in an existing file?

**Comment by xpicio** [comment]
@uhafner i suppose should be useful both requirements 🙂

**Comment by uhafner** [comment]
I updated the documentation. PRs are always welcome 🙏
