### ISSUE TITLE
Use report name of jacoco.xml report

### ISSUE THREAD

**Issue by reitzmichnicht** [jenkinsci/code-coverage-api-plugin#73]
When using the coverage plugin for a multi-module maven project with jacoco I get reports named: jacoco:jacoco and jacoco:jacoco1

These reports have well formed named in the jacoco.xml report that could be used for visualization:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>...<report name="Foo Bar">`

Kind regards and I really enjoy this great plugin
Michael

**Comment by cizezsy** [comment]
@reitzmichnicht Great catch, fixed it in version 1.0.9~

**Comment by reitzmichnicht** [comment]
Thanks for the fast fix.
I managed to update the plugin today and gave it a try. Looks much better now, but could still be improved:
Module1: jacoco.xml(1)(click to see more details)
Module2: jacoco.xml(2)(click to see more details)
Module3: jacoco.xml(click to see more details)

First there is a missing space before (click to see more details)
Second instead of incrementing numbers for jacoco.xml I would prefer seeing just the file name or if it needs to be distinguishable include the relative path to the file.

**Comment by cizezsy** [comment]
@reitzmichnicht You are right. that will make the report name easier to understand. I will fix improve them in next release. Thanks :P

**Comment by viceice** [comment]
what about using the tag as report title instead of the path so it would be more meaningful

![image](https://user-images.githubusercontent.com/1798109/88140620-57930b00-cbf2-11ea-823d-05e977503948.png)
