### ISSUE TITLE
Cannot see sources for jacoco in gradle multi project

### ISSUE THREAD

**Issue by staffanf** [jenkinsci/code-coverage-api-plugin#74]
Hi,
I'm trying to convert to this plugin from the old jacoco plugin.
I'm using a multibranch declarative pipeline job to build a gradle multi project build.
The definition is like this.
```
publishCoverage adapters: [jacocoAdapter('*/build/reports/jacoco/test/jacocoTestReport.xml')], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')
```

This finds the test reports and names them jacocoTestReport, jacocoTestReport1 etc. in the gui.
It also says this in the log:
```
15:52:16  Publishing Coverage report....
15:52:17  A total of 7 reports were found
15:52:17  Source File Navigation is enabled - Current level: STORE_LAST_BUILD
15:52:17  377 source files need to be copied
```
But I can't find any way to dig into source file reports anywhere.
If I click into "https://jenkins/job/jobName/7/coverage/jacoco__jacocoTestReport/", I can find the detailed report but I cant find the file breakdown anywhere.

Is there anyway I can debug what's wrong?

**Comment by cizezsy** [comment]
@staffanf Hi, You may need to click the name of the child summary chart (the bottom chart) item to enter the next level. Then, you can see source file in the File level :)

![image](https://user-images.githubusercontent.com/22002278/55000669-fd8a3180-500d-11e9-958e-4d61a2f8bffa.png)

**Comment by staffanf** [comment]
omg... you can't imagine how much I have clicked around in these reports without noticing that...
In my example I only have one line called "project" and I clicked everywhere in the tables and headers.
Anything to make this more obvious. The are no groups in my report files so the first level is kinda strange here.
I guess I could close this, but I think some way of increasing the obviousness of clicking on those links would be nice.

**Comment by cizezsy** [comment]
@staffanf yeah....you are right, I will add a hint in the report page to tell users those links are clickable...Sorry for the inconvenience :(

**Comment by staffanf** [comment]
Cool, thanks for the feedback. Feel free to close this when you think it's enough.

**Comment by cizezsy** [comment]
@staffanf Added it in version 1.0.9, thanks very much for your feedback :P
