### ISSUE TITLE
coverage files are not read from the workspace directory on agents

### ISSUE THREAD

**Issue by tkleiber** [jenkinsci/code-coverage-api-plugin#76]
For my stage I use a defined node

  agent {
    node {
      label 'XXX'
    }
  }

The files from code coverage are created below the workspace directory for the jenkins node (WORKSPACE environment variable), which is remote and has different access rights.

The plugin seems to read only the build directory under the jobs directory on the jenkins master.

**Comment by cizezsy** [comment]
@tkleiber what's your plugin's version?

**Comment by tkleiber** [comment]
1.0.9

**Comment by cizezsy** [comment]
@tkleiber Hi, sorry for the late reply, I am a little busy these days :(. This plugin should be able to read the coverage report from the agent. Could you provide more details about your plugin's configuration?

**Comment by tkleiber** [comment]
Configuration is similar to following

```groovy
pipeline {
  agent {
    node {
      label 'DB_11.2.0.4.0'
    }
  }
  stages {
    stage('utPLSQL') {
      steps {
...
        echo 'WORKSPACE is ' + WORKSPACE
        publishCoverage adapters: [istanbulCoberturaAdapter('**/ut_coverage_cobertura_reporter.xml')]
      }
    }
  }
}
```

But the output shows that the jobs directory is read instead of the workspace:

```
[Pipeline] echo
WORKSPACE is /oraias/appl/jenkins_oraias/workspace/test_utplsql_coverage_as_cobertura
[Pipeline] publishCoverage
Publishing Coverage report....
report /var/lib/jenkins/jobs/test_utplsql_coverage_as_cobertura/builds/13/ut_coverage_cobertura_reporter.xml for Istanbul (Cobertura reporter) has met some errors: javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: External DTD: Failed to read external DTD 'coverage-04.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.
A total of 0 reports were found
```

**Comment by cizezsy** [comment]
@tkleiber When this plugin failed to transform XML file, it will disable DTD validation and transform it again - [code](https://github.com/jenkinsci/code-coverage-api-plugin/blob/dev/src/main/java/io/jenkins/plugins/coverage/adapter/util/XMLUtils.java#L95).

But I omit the all `exception` thrown by the `readXMLtoDocumentWithoutXSD` method and throws the `TransformerExection` directly. As a result, we cannot know what the real problem is. This is absolutely a fault...

So could you help me to give me a simple version of your report? Or, you can wait for me to release the next version that has more logs. Thanks very much!

**Comment by tkleiber** [comment]
The parsing error happens because no file is found in the job directory, so your copy does not work:

```
[Pipeline] echo
WORKSPACE is /oraias/appl/jenkins_oraias/workspace/test_utplsql_coverage_as_cobertura
[Pipeline] publishCoverage
Publishing Coverage report....
report /var/lib/jenkins/jobs/test_utplsql_coverage_as_cobertura/builds/14/ut_coverage_cobertura_reporter.xml for Istanbul (Cobertura reporter) has met some errors: javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: External DTD: Failed to read external DTD 'coverage-04.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.
A total of 0 reports were found
```
Here you see that the file ut_coverage_cobertura_reporter.xml is missing in the jobs directory:

```
~>ls -R /oraias/appl/jenkins_oraias/workspace/test_utplsql_coverage_as_cobertura
/oraias/appl/jenkins_oraias/workspace/test_utplsql_coverage_as_cobertura:
resultDir

/oraias/appl/jenkins_oraias/workspace/test_utplsql_coverage_as_cobertura/resultDir:
ut_coverage_cobertura_reporter.xml  ut_documentation_reporter_db.log  ut_xunit_reporter.xml
~> find /var/lib/jenkins/jobs/test_utplsql_coverage_as_cobertura/builds/14/libs -name ut_coverage_cobertura_reporter.xml

```

**Comment by cizezsy** [comment]
@tkleiber 
- This plugin will delete all copied files and you cannot find them after build. 
- Also, here you can see that logs output`...Failed to read external DTD 'coverage-04.dtd'`. This DTD file name comes from your report. 

So, the report is copied successfully.

**Comment by tkleiber** [comment]
Ok - then I misinterpreted the message "A total of 0 reports were found".
I attach the cobertura file, maybe you can see the problem?
[ut_coverage_cobertura_reporter.zip](https://github.com/jenkinsci/code-coverage-api-plugin/files/3161353/ut_coverage_cobertura_reporter.zip)

**Comment by cizezsy** [comment]
@tkleiber You report format is wrong.

For example, in the end of line 39 a newline divide `number`, so report cannot be parsed.
```
...="93" hits="0" branch="false"/><line numb
er="94" hits="0" branch="false"/><line...
```

**Comment by tkleiber** [comment]
Thanks, I will create an issue on the framework, which creates the cobertura xml!
