### ISSUE TITLE
Copying source files is extremely slow

### ISSUE THREAD

**Issue by reitzmichnicht** [jenkinsci/code-coverage-api-plugin#77]
We have 240 source files that are copied by the setting sourceFileResolver: sourceFiles('STORE_LAST_BUILD'),

This increases build time by 3 minutes.
Is there any possibility to speed this up?

**Comment by cizezsy** [comment]
@reitzmichnicht Hi, I have released a new version 1.0.10. I used multiple threads to copy source files, it should speed this up.  Could you check this in the new version? Thanks!

**Comment by reitzmichnicht** [comment]
Hi down from 180 seconds to 2 seconds
👍

**Comment by cizezsy** [comment]
@reitzmichnicht I use threads to copy source files in the background to fix this issue, but it will cause problems when using transient agent :( https://github.com/jenkinsci/code-coverage-api-plugin/issues/82. There is no easy solution for that now, so I will change codes to wait for all copy tasks ended. That will increase time but should quicker than 180 seconds.
