### ISSUE TITLE
Support for OpenCover format

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/code-coverage-api-plugin#770]
### What feature do you want to see added?

Add support for OpenCover format.

Extension plugin was originally developed in https://github.com/jenkinsci/opencover-plugin (not by me, but using it)

But it's using the deprecated `publishCoverage` step.

We should have the parser "moved" to recordCoverage step and this plugin.

Sadly I don't have bandwidth to submit a PR, but maybe could be an hacktober fest issue ?

Probably the adoption of OpenCover decreased, but there are still many tool supporting it's format for reports (like SonarQube)

**Comment by uhafner** [comment]
Since the Jenkins open-cover did not provide too much useful tests I skipped that parser up to now. Can you please attach a coverage file that can be used in tests?

**Comment by jonesbusy** [comment]
Sure! Let me try to find one for this ticket (Probably I can take the one from the plugin).

The only real one I have is 10MB and need anonymization.

**Comment by jonesbusy** [comment]
Reading the deprecation notice I think it become a bit more urgent. I think we can use for now resources from there : https://github.com/jenkinsci/opencover-plugin/tree/main/src/test/resources/io/jenkins/plugins/opencover

Perhaps the test coverage is not ideal but is better than nothing. At least to keep minimal functionality of displaying opencover reports on Jenkins.

**Comment by uhafner** [comment]
Yes, it makes sense to start with these files (and maybe the parser). Interested in creating a PR?

**Comment by jonesbusy** [comment]
Yes I will, probably I will ping you there https://github.com/jenkinsci/coverage-model/pull/46 if I need some support
