### ISSUE TITLE
No source files are displayed on the Files tab

### ISSUE THREAD

**Issue by hicnar** [jenkinsci/code-coverage-api-plugin#784]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.414.2
OS: Mac OS X - 10.15.7
Java: 11.0.10 - Oracle Corporation (OpenJDK 64-Bit Server VM)
---
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.2.1-1.1
authentication-tokens:1.53.v1c90fd9191a_b_
backup:1.6.1
bootstrap5-api:5.3.2-1
bouncycastle-api:2.29
branch-api:2.1128.v717130d4f816
build-blocker-plugin:1.7.9
build-monitor-plugin:1.14-745.ve2023a_305f40
build-timeout:1.31
built-on-column:1.4
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloud-stats:320.v96b_65297a_4b_b_
cloudbees-folder:6.848.ve3b_fd7839a_81
code-coverage-api:4.8.0
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.10.0-78.v3e7b_ea_d5a_fe1
conditional-buildstep:1.4.3
config-file-provider:959.vcff671a_4518b_
copyartifact:722.v0662a_9b_e22a_c
credentials:1293.vff276f713473
credentials-binding:636.v55f1275c7b_27
cucumber-reports:5.7.6
dark-theme:336.v02165cd8c2ee
data-tables-api:1.13.6-4
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-java-api:3.3.1-79.v20b_53427e041
docker-plugin:1.5
docker-workflow:572.v950f58993843
durable-task:523.va_a_22cf15d5e0
echarts-api:5.4.0-6
email-ext:2.102
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
external-monitor-job:215.v2e88e894db_f8
font-awesome-api:6.4.2-1
forensics-api:2.3.0
git:5.2.0
git-client:4.5.0
git-server:99.va_0826a_b_cdfa_d
github:1.37.3
github-api:1.316-451.v15738eef3414
github-branch-source:1741.va_3028eb_9fd21
gradle:2.8.2
groovy:457.v99900cb_85593
htmlpublisher:1.32
instance-identity:173.va_37c494ec4e5
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.2-350.v0c2f3f8fc595
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:73.vddf737284550
jenkins-multijob-plugin:623.v03401733c9a_9
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.18-1
jobConfigHistory:1229.v3039470161a_d
jquery:1.12.4-1
jquery3-api:3.7.1-1
jsch:0.2.8-65.v052c39de79b_2
junit:1240.vf9529b_881428
kpp-management-plugin:105.v767485951b_d2
ldap:701.vf8619de9160a_
lockable-resources:1185.v0c528656ce04
mailer:463.vedf8358e006b_
matrix-auth:3.2.1
matrix-project:808.v5a_b_5f56d6966
maven-plugin:3.23
mina-sshd-api-common:2.10.0-69.v28e3e36d18eb_
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
multibranch-scan-webhook-trigger:1.0.9
naginator:1.421.v85c11e2db_507
nested-view:1.33
nodelabelparameter:1.12.0
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
pam-auth:1.10
parameterized-trigger:2.46
pipeline-build-step:505.v5f0844d8d126
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2144.v077a_d1928a_40
pipeline-model-definition:2.2144.v077a_d1928a_40
pipeline-model-extensions:2.2144.v077a_d1928a_40
pipeline-rest-api:2.33
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2144.v077a_d1928a_40
pipeline-stage-view:2.33
pipeline-utility-steps:2.16.0
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.4.0
prism-api:1.29.0-8
publish-over:0.22
publish-over-ssh:1.25
rebuild:320.v5a_0933a_e7d61
resource-disposer:0.23
run-condition:1.7
scm-api:676.v886669a_199a_a_
scoring-load-balancer:59.vf791549fa_989
script-security:1275.v23895f409fb_d
snakeyaml-api:2.2-111.vc6598e30cc65
solarized-theme:0.1
ssh-agent:333.v878b_53c89511
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
ssh-steps:2.0.65.vd26b_5b_9b_de4d
sshd:3.312.v1c601b_c83b_0e
structs:325.vcb_307d2a_2782
theme-manager:211.vef2a_42c645a_b_
timestamper:1.26
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
uno-choice:2.7.2
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3793.v65dec41c3a_c3
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1348.v32a_a_f150910e
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45 
```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller runs on Mac, agents run on Ubuntu Linux.

### Reproduction steps

I just run the build generate multiple jacoco exec files, merge them and pass to the stage that generates coverage reports. Some two months ago everything worked, but all of the sudden source files stopped to be displayed.
There were not changes to the project or the way the reports are generated or merged, there's also nothing related to Coverage generation in the Jenkins log.

### Expected Results

I should be able to select source files that should be displayed on the Files tab.

### Actual Results

No source files are displayed

### Anything else?

Everything else seems to be working just fine, Can see Overview, Line, Batch and Instruction coverage.
Report data is generated by Jacoco, here's the section in the pipeline definition that generates coverage reports

                recordCoverage(
                    id: 'jacoco', 
                    name: 'Code Coverage', 
                    skipPublishingChecks: true, 
                    sourceCodeRetention: 'EVERY_BUILD', 
                    sourceDirectories: [[path: 'src']], 
                    tools: [[pattern: 'target/jacoco-all.xml']]
                )

```[tasklist]
### Tasks
```

**Comment by uhafner** [comment]
Can you please add more details? Screenshot? Are there no rows? Are there no links? How did you configure the plug-in?

**Comment by hicnar** [comment]
![image](https://github.com/jenkinsci/code-coverage-api-plugin/assets/1816194/867b4844-231a-46e9-9195-f7211eb565ac)
![image](https://github.com/jenkinsci/code-coverage-api-plugin/assets/1816194/7d34211a-ac5e-4912-b095-909dbfb0e8a4)
![image](https://github.com/jenkinsci/code-coverage-api-plugin/assets/1816194/8cbcb748-6959-4983-8711-b759478d0049)
![image](https://github.com/jenkinsci/code-coverage-api-plugin/assets/1816194/1198ae9d-0858-4383-a6ed-869c2f0393d1)
![image](https://github.com/jenkinsci/code-coverage-api-plugin/assets/1816194/6c92f895-47b3-404b-bc90-8b94f7af61fc)
plugin config included in the original message (see above)

**Comment by uhafner** [comment]
How does your step look like? Are there exceptions in the Jenkins log? Or in the browser? Do you still have Prototype.js enabled?

**Comment by uhafner** [comment]
Can you see the files here: https://ci.jenkins.io/job/Plugins/job/code-coverage-api-plugin/job/master/417/coverage/

**Comment by hicnar** [comment]
Not sure you read my original post above, but here it is again:

       stage('Publish Reports') {
            steps {
                recordCoverage(
                    id: 'jacoco', 
                    name: 'Code Coverage', 
                    skipPublishingChecks: true, 
                    sourceCodeRetention: 'EVERY_BUILD', 
                    sourceDirectories: [[path: './jacoco']], 
                    tools: [[pattern: 'target/jacoco-all.xml']]
                )
            }
        }

No there are no exceptions in Jenkins logs, there is the following exception logged when the Files tab is chosen

![image](https://github.com/jenkinsci/code-coverage-api-plugin/assets/1816194/fad21616-3a53-4110-b8ed-5822c1ced5fc)

Yep can see the files when I open the link above. 
How do I know whether I have Prototype.js enabled?

**Comment by uhafner** [comment]
> Not sure you read my original post above, but here it is again:

Due to a missing closed tag the rest of your description was wrapped in the environment.

**Comment by uhafner** [comment]
https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/

**Comment by uhafner** [comment]
It seems that a conflict on the JS UI side prevents the rendering. Just to make sure if this is a browser or Jenkins problem: Can you see the coverage results of our Jenkins instance, see link above? Do other users have the same problem?

**Comment by uhafner** [comment]
Can you please create a screenshot of the loaded JS libraries? Maybe that helps to see what is different on your instance. (There should be a difference in your browser for your instance and our Jenkins CI instance as well). I created one for my instance with Chrome (show the columns name and path):

![Bildschirmfoto 2023-10-05 um 08 43 10](https://github.com/jenkinsci/code-coverage-api-plugin/assets/503338/d2b249d9-daaa-4f48-8518-f0d0090eebea)

**Comment by uhafner** [comment]
I think this is the same as https://github.com/jenkinsci/lockable-resources-plugin/issues/567

**Comment by hicnar** [comment]
Fixed indeed! Cheers! How comes it was only me complaining?

**Comment by uhafner** [comment]
> Fixed indeed! Cheers! How comes it was only me complaining?

Well, on my machine the error just showed up in the browser log. The rows where correctly shown..
