### ISSUE TITLE
Feature request: View column for coverage

### ISSUE THREAD

**Issue by bmerry** [jenkinsci/code-coverage-api-plugin#79]
With the old Cobertura plugin, I could add a column to a view to show the coverage next to each project (and select which coverage measure to list). It would be nice to be able to do the same with this plugin.

**Comment by cizezsy** [comment]
@bmerry Add column view in #95 :P

**Comment by bmerry** [comment]
Thanks!

**Comment by cizezsy** [comment]
You can try it in version 1.0.12 now :P

**Comment by bmerry** [comment]
Looks like it's working. Thanks!
