### ISSUE TITLE
Missing group tag for jacoco reports generated by gradle

### ISSUE THREAD

**Issue by f2rf2r** [jenkinsci/code-coverage-api-plugin#81]
Jacoco reports generated by gradle's JacocoReport task doesn't contain a `group` tag, they just go directly from `report` tag to `package` tags. Currently this plugin expects that there will be a group tag, which means it won't process the gradle jacoco report correctly. Is it possible to update the plugin to allow the `group` tag to be omitted to support gradle?

Currently the result just looks like this:
![image](https://user-images.githubusercontent.com/2636474/57388622-8e643900-7186-11e9-9feb-c7bce020c5b2.png)

**Comment by cizezsy** [comment]
@f2rf2r Sure~ JaCoCo XML report DTD allows `package` under `report` tag, I omit that before :(. I will fix it in next release.

**Comment by cizezsy** [comment]
@f2rf2r I have checked the codes and found it does deal with the situation that there is no group tag. So could you give me a simple version of your coverage report? Thanks!

**Comment by cizezsy** [comment]
@f2rf2r Hi, I test your report and it works well in my computer...
<img width="827" alt="屏幕快照 2019-05-20 上午11 15 19" src="https://user-images.githubusercontent.com/22002278/57994720-1cc6ac00-7af1-11e9-9ce5-261cd1b712dc.png">
 
What's your plugin's version? Could you provide your console log? Thanks!

**Comment by f2rf2r** [comment]
Turns out this is due some issue with our configuration and not related to the plugin. Gonna close this.
