### ISSUE TITLE
Globals Thresholds show repeated optional value

### ISSUE THREAD

**Issue by TinyZzh** [jenkinsci/code-coverage-api-plugin#84]
![image](https://user-images.githubusercontent.com/5763397/57523535-cd95b400-7357-11e9-93cf-15dcb06665ae.png)

version
jenkins：2.164.2
code coverage-api: 1.0.10

**Comment by cizezsy** [comment]
@TinyZzh Actually, they are different thresholds, one comes from Cobertura, one comes from Istanbul. This is a problem, I will fix it :(

For now, you can config it in adapter's level :P
