### ISSUE TITLE
Jacoco coverage report not showing when used with Jenkins Pipeline

### ISSUE THREAD

**Issue by yashwanthupsc** [jenkinsci/code-coverage-api-plugin#89]
Hi Guys
I am trying to generate coverage report with jenkins pipeline but after the build it is not showing, which is not the case with freestyle project where it is working properly.
the pipeline script is
"post {
always {
publishCoverage adapters: [jacocoAdapter('/target/site/jacoco/jacoco.xml')]
} }"
output in the log showing
"Publishing Coverage report...."
build is successful but report missing.
Build Command : mvn clean package sonar:sonar
Thanks

**Comment by cizezsy** [comment]
@yashwanthupsc If the report can be found in the freestyle project, it should be able to be found in the pipeline project. Could you check if your build command really generates coverage report in the correct path?

**Comment by yashwanthupsc** [comment]
@cizezsy it is working perfectly fine now. I added the correct path but the issue was because of sonar. The report was not generated because i added quality gate time out.

**Comment by cizezsy** [comment]
@yashwanthupsc great, so I guess I can close this issue :)
