### ISSUE TITLE
"Cannot found source..." error with Cobertura Reports with Fully Qualified Filename property

### ISSUE THREAD

**Issue by Chocrates** [jenkinsci/code-coverage-api-plugin#90]
Repro Steps:
Generate your Cobertura reports with [Coverlet](https://github.com/tonerdo/coverlet) using the --format cobertura flag
Validate that the `filename` property is filled with the fully qualified path of the file.
Send the report to the code-coverage-api and save the last build
Notice that the source cannot be found. 

Note: I will update the Repro steps with something more concrete this evening.

**Comment by TrymBeast** [comment]
@cizezsy Is there any prevision to fix this?
I'm hitting the same problem, but in my case I use dotCover to generate the coverage report, than I convert to Cobertura format using the ReportGenerator tool, and the filename property in the report has the full path of the source file.

**Comment by cizezsy** [comment]
Fix in version 1.1.2 :P
