### ISSUE TITLE
java.io.IOException: Expecting Ant GLOB pattern for absolute paths

### ISSUE THREAD

**Issue by SoftwareApe** [jenkinsci/code-coverage-api-plugin#92]
Reproduction:
use absolute path, e.g.

    '/var/jenkins/...'

Publishing step crashes with:
     java.io.IOException: Expecting Ant GLOB pattern

System:
Ubuntu 16.04. using llvmAdapter (but path handling is in this repo I think).

**Comment by tempora-mutantur** [comment]
Hello, @SoftwareApe 
I think that this is the common interface to use Ant Glob pattern as input. Most of plugins use such syntax, like JUnit, etc.
ICYDK you can switch the working directory using `dir` and launch `publishCoverage` from there.
Thank you.
