### ISSUE TITLE
nullPointerException in setOwner

### ISSUE THREAD

**Issue by SoftwareApe** [jenkinsci/code-coverage-api-plugin#93]
Reproduction:
use relative path that points nowhere, e.g.

    'abc/coverage.json'

Publishing step crashes with:
    java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.get(TreeMap.java:278)

System:
Ubuntu 16.04. using llvmAdapter (but path handling is in this repo I think).

Expected behavior:
* Check if path exists
* If not, give a notification of which (absolute) path was tried (right now it's not clear from the UI that the path has to be relative to the ${WORKSPACE} variable even if Jenkins is in another workspace).

Additional UX concerns:
* Maybe could rename from path to pathRelativeToWorkspace (as absolute paths aren't handled properly either, see #92 ) or handle absolute paths as well as relative paths to the current directory in which Jenkins is operating (using the dir command).

**Comment by SoftwareApe** [comment]
Correction, also maybe regarding #94 I added **/ to the path and it did find the report (according to the message), however I still get this NullPointerException. Tracing it further it comes from some setOwner function:

    java.lang.NullPointerException
        at java.util.TreeMap.getEntry(TreeMap.java:347)
        at java.util.TreeMap.get(TreeMap.java:278)
        **at io.jenkins.plugins.coverage.targets.CoverageResult.setOwner(CoverageResult.java:471)**
        at io.jenkins.plugins.coverage.targets.CoverageResult.setOwner(CoverageResult.java:462)
        at io.jenkins.plugins.coverage.targets.CoverageResult.setOwner(CoverageResult.java:462)
        at io.jenkins.plugins.coverage.targets.CoverageResult.setOwner(CoverageResult.java:462)
        at io.jenkins.plugins.coverage.targets.CoverageResult.setOwner(CoverageResult.java:462)
        at     io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport(CoverageProcessor.java:89)
        at io.jenkins.plugins.coverage.CoveragePublisher.perform(CoveragePublisher.java:91)
        at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
        at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
        at 

If this is still the same file the owner may be null and thus not working. Who is this owner and how can this be null?

**Comment by cizezsy** [comment]
@SoftwareApe Thanks for your feedback, but I cannot reproduce this error in my computer (macOs Mojave 10.14.4). 

If the path refers to a non-existed file, this plugin will not execute setOwner. It will find files in the workspace by the input path. If no files found, it will log the error message and stop this step. 

Also, The setOwner method is called to traverse the tree built by coverage report. In your console logs, this method called **five** times. So, there must have a tree built successfully. Could you confirm your workspace that if a file exists in this path?

Thanks!

**Comment by cizezsy** [comment]
@SoftwareApe 

1. When you using the first path `abc/coverage.json`, Does the log said it finds coverage report? In your first case, this plugin seems to find a coverage report. (although, you say this path points to nowhere).
2. The owner must exist. Because it passed by Jenkins and mark with an `@Nonnull` annotation.  
3. Your error is caused by an incorrect Coverage tree built from the coverage report. (This is why I ask you for coverage report..)
4. The wildcard is not related to this issue I think.
5. Sure, you can run`mvn package` to compile this plugin, and install the generated `code-coverage-api.hpi` file in `target` directory to your Jenkins instance. Or, you can run `mvn hpi:run` to start a Jenkins with this plugin locally. To debug it, you can run `mvnDebug hpi:run`, so you can debug it in your IDE

Thanks :P

**Comment by SoftwareApe** [comment]
@cizezsy I built the current version from dev using mvn package and it works (no other settings changed). So maybe this issue is already resolved by previous changes.

Thank you for your help! Do you know when the next release will be published?

**Comment by cizezsy** [comment]
@SoftwareApe Probably this week, there are several bugs I need to fix :P
