### ISSUE TITLE
No reports were found

### ISSUE THREAD

**Issue by SoftwareApe** [jenkinsci/code-coverage-api-plugin#94]
Reproduction:
* Use llvmAdapter
* use relative path from Jenkins workspace to report e.g.

    'path/to/coverage.json'

Publishing step outputs:
    Publishing Coverage Reports...
    No reports were found

System:
Ubuntu 16.04. using llvmAdapter (but the error messages comes from this repo) and clang 9.

Expected behavior:
* Show coverage
* If it can't find the report, be more verbose about what it didn't find. (Especially since a non-existent path leads to NPE (#93) an absolute path leads to ANT exception (#92), so not crashing to me means it found the report but can't handle it?).

In order to avoid confusion:
The coverage.json is there and looks valid. It was created using llvm-cov export as shown in the guide.

**Comment by cizezsy** [comment]
@SoftwareApe Is this issue still exists when using the version built from dev?
