### ISSUE TITLE
Support of coverage reports based on multiple files

### ISSUE THREAD

**Issue by andre2007** [jenkinsci/code-coverage-api-plugin#96]
The coverage report for the D Programming Language is based on multiple files. In your project root folder you will have a flat list of *.lst files. For each D module in your project you will have a LST file.

File ```source-lib.lst```
```
       |int add(int a, int b)
       |{
      1|    return a + b;
       |}
       |
       |int substract(int a, int b)
       |{
0000000|    return a - b;
       |}
source/lib.d is 50% covered
```

File ```source-app.lst```
```
       |import std.stdio;
       |import lib;
       |
       |version (unittest)
       |{
       |    int main(string[] args)
       |    {
       |        import dunit;
       |
      1|        return dunit_main(args);
       |    }
       |}
       |else
       |{
       |    void main()
       |    {
       |    }
       |}
       |
       |unittest
       |{
      1|    assert(5 == add(2, 3));
       |}
source/app.d is 100% covered
```

Does the code-coverage-api-plugin supports multiple files? I wonder because this method expects exactly 1 file:
https://github.com/jenkinsci/code-coverage-api-plugin/blob/dev/src/main/java/io/jenkins/plugins/coverage/adapter/CoverageReportAdapter.java#L58

**Comment by cizezsy** [comment]
@andre2007 It does support multiple files. Although, this method only except 1 file, it can merge multiple reports into 1 report: https://github.com/jenkinsci/code-coverage-api-plugin/blob/dev/src/main/java/io/jenkins/plugins/coverage/CoverageProcessor.java#L84.

**Comment by andre2007** [comment]
Thanks @cizezsy . Do you know why this coding fails with a null pointer exception while calling method getLocalName on variable current?
```java
    @Override
    public Document convert(File source) throws CoverageException {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder;
        try {
            builder = factory.newDocumentBuilder();
        } catch (ParserConfigurationException e) {
            throw new CoverageException(e);
        }

        Document document = builder.newDocument();
        Element rootElement = document.createElement("report");
        rootElement.setAttribute("name", "abc");
        document.appendChild(rootElement);

        Element fileElement = document.createElement("file");
        fileElement.setAttribute("name", source.getPath());
        rootElement.appendChild(fileElement);
        return document;
    }

        @Override
        protected CoverageResult processElement(Element current, CoverageResult parentResult) {
            CoverageResult result = null;
            // NPE Here 
            switch (current.getLocalName()) {
```

**Comment by cizezsy** [comment]
Could you run your plugin with `mvnDebug hpi:run` to enable debug to see what exactly happened when calling `getLocalName`?

**Comment by cizezsy** [comment]
@andre2007 For elements created by `Document.createElement()`, you may need to use `getTagName()` instead of `getLocalName`.

**Comment by andre2007** [comment]
Thanks that is working.

I close this issue as the questions are solved.
